In [2]:
import warnings
warnings.filterwarnings('ignore')

In [18]:
from pathlib import Path
import shutil
import pandas as pd
import os
import numpy as np

In [ ]:

SRC_ROOT = Path("stdata")   
DST_ROOT = Path("data")     
CATEGORIES = ["EEG", "GSR", "PSY"]

for cat in CATEGORIES:
    (DST_ROOT / cat).mkdir(parents=True, exist_ok=True)

for i in range(1, 39):  
    src_folder = SRC_ROOT / str(i)

    if not src_folder.exists():
        print(f"Skipping: source folder not found -> {src_folder}")
        continue

    for cat in CATEGORIES:
        filename = f"{i}_{cat}.csv"
        src_file = src_folder / filename
        dst_file = DST_ROOT / cat / filename

        if not src_file.exists():
            print(f"Skipping (file not found): {src_file}")
            continue


        shutil.copy2(src_file, dst_file)
        print(f"Copied: {src_file} -> {dst_file}")

print("All done.")

Copied: stdata\1\1_EEG.csv -> data\EEG\1_EEG.csv
Copied: stdata\1\1_GSR.csv -> data\GSR\1_GSR.csv
Copied: stdata\1\1_PSY.csv -> data\PSY\1_PSY.csv
Copied: stdata\2\2_EEG.csv -> data\EEG\2_EEG.csv
Copied: stdata\2\2_GSR.csv -> data\GSR\2_GSR.csv
Copied: stdata\2\2_PSY.csv -> data\PSY\2_PSY.csv
Copied: stdata\3\3_EEG.csv -> data\EEG\3_EEG.csv
Copied: stdata\3\3_GSR.csv -> data\GSR\3_GSR.csv
Copied: stdata\3\3_PSY.csv -> data\PSY\3_PSY.csv
Copied: stdata\4\4_EEG.csv -> data\EEG\4_EEG.csv
Copied: stdata\4\4_GSR.csv -> data\GSR\4_GSR.csv
Copied: stdata\4\4_PSY.csv -> data\PSY\4_PSY.csv
Copied: stdata\5\5_EEG.csv -> data\EEG\5_EEG.csv
Copied: stdata\5\5_GSR.csv -> data\GSR\5_GSR.csv
Copied: stdata\5\5_PSY.csv -> data\PSY\5_PSY.csv
Copied: stdata\6\6_EEG.csv -> data\EEG\6_EEG.csv
Copied: stdata\6\6_GSR.csv -> data\GSR\6_GSR.csv
Copied: stdata\6\6_PSY.csv -> data\PSY\6_PSY.csv
Copied: stdata\7\7_EEG.csv -> data\EEG\7_EEG.csv
Copied: stdata\7\7_GSR.csv -> data\GSR\7_GSR.csv
Copied: stdata\7\7_PSY.csv -> data\PSY\7_PSY.csv
Copied: stdata\8\8_EEG.csv -> data\EEG\8_EEG.csv
Copied: stdata\8\8_GSR.csv -> data\GSR\8_GSR.csv
Copied: stdata\8\8_PSY.csv -> data\PSY\8_PSY.csv
Copied: stdata\9\9_EEG.csv -> data\EEG\9_EEG.csv
Copied: stdata\9\9_GSR.csv -> data\GSR\9_GSR.csv
Copied: stdata\9\9_PSY.csv -> data\PSY\9_PSY.csv
Copied: stdata\10\10_EEG.csv -> data\EEG\10_EEG.csv
Copied: stdata\10\10_GSR.csv -> data\GSR\10_GSR.csv
Copied: stdata\10\10_PSY.csv -> data\PSY\10_PSY.csv
Copied: stdata\11\11_EEG.csv -> data\EEG\11_EEG.csv
Copied: stdata\11\11_GSR.csv -> data\GSR\11_GSR.csv
Copied: stdata\11\11_PSY.csv -> data\PSY\11_PSY.csv
Copied: stdata\12\12_EEG.csv -> data\EEG\12_EEG.csv
Copied: stdata\12\12_GSR.csv -> data\GSR\12_GSR.csv
Copied: stdata\12\12_PSY.csv -> data\PSY\12_PSY.csv
Copied: stdata\13\13_EEG.csv -> data\EEG\13_EEG.csv
Copied: stdata\13\13_GSR.csv -> data\GSR\13_GSR.csv
Copied: stdata\13\13_PSY.csv -> data\PSY\13_PSY.csv
Copied: stdata\14\14_EEG.csv -> data\EEG\14_EEG.csv
Copied: stdata\14\14_GSR.csv -> data\GSR\14_GSR.csv
Copied: stdata\14\14_PSY.csv -> data\PSY\14_PSY.csv
Copied: stdata\15\15_EEG.csv -> data\EEG\15_EEG.csv
Copied: stdata\15\15_GSR.csv -> data\GSR\15_GSR.csv
Copied: stdata\15\15_PSY.csv -> data\PSY\15_PSY.csv
Copied: stdata\16\16_EEG.csv -> data\EEG\16_EEG.csv
Copied: stdata\16\16_GSR.csv -> data\GSR\16_GSR.csv
Copied: stdata\16\16_PSY.csv -> data\PSY\16_PSY.csv
Copied: stdata\17\17_EEG.csv -> data\EEG\17_EEG.csv
Copied: stdata\17\17_GSR.csv -> data\GSR\17_GSR.csv
Copied: stdata\17\17_PSY.csv -> data\PSY\17_PSY.csv
Copied: stdata\18\18_EEG.csv -> data\EEG\18_EEG.csv
Copied: stdata\18\18_GSR.csv -> data\GSR\18_GSR.csv
Copied: stdata\18\18_PSY.csv -> data\PSY\18_PSY.csv
Copied: stdata\19\19_EEG.csv -> data\EEG\19_EEG.csv
Copied: stdata\19\19_GSR.csv -> data\GSR\19_GSR.csv
Copied: stdata\19\19_PSY.csv -> data\PSY\19_PSY.csv
Copied: stdata\20\20_EEG.csv -> data\EEG\20_EEG.csv
Copied: stdata\20\20_GSR.csv -> data\GSR\20_GSR.csv
Copied: stdata\20\20_PSY.csv -> data\PSY\20_PSY.csv
Copied: stdata\21\21_EEG.csv -> data\EEG\21_EEG.csv
Copied: stdata\21\21_GSR.csv -> data\GSR\21_GSR.csv
Copied: stdata\21\21_PSY.csv -> data\PSY\21_PSY.csv
Copied: stdata\22\22_EEG.csv -> data\EEG\22_EEG.csv
Copied: stdata\22\22_GSR.csv -> data\GSR\22_GSR.csv
Copied: stdata\22\22_PSY.csv -> data\PSY\22_PSY.csv
Copied: stdata\23\23_EEG.csv -> data\EEG\23_EEG.csv
Copied: stdata\23\23_GSR.csv -> data\GSR\23_GSR.csv
Copied: stdata\23\23_PSY.csv -> data\PSY\23_PSY.csv
Copied: stdata\24\24_EEG.csv -> data\EEG\24_EEG.csv
Copied: stdata\24\24_GSR.csv -> data\GSR\24_GSR.csv
Copied: stdata\24\24_PSY.csv -> data\PSY\24_PSY.csv
Copied: stdata\25\25_EEG.csv -> data\EEG\25_EEG.csv
Copied: stdata\25\25_GSR.csv -> data\GSR\25_GSR.csv
Copied: stdata\25\25_PSY.csv -> data\PSY\25_PSY.csv
Copied: stdata\26\26_EEG.csv -> data\EEG\26_EEG.csv
Copied: stdata\26\26_GSR.csv -> data\GSR\26_GSR.csv
Copied: stdata\26\26_PSY.csv -> data\PSY\26_PSY.csv
Copied: stdata\27\27_EEG.csv -> data\EEG\27_EEG.csv
Copied: stdata\27\27_GSR.csv -> data\GSR\27_GSR.csv
Copied: stdata\27\27_PSY.csv -> data\PSY\27_PSY.csv
Copied: stdata\28\28_EEG.csv -> data\EEG\28_EEG.csv
Copied: stdata\28\28_GSR.csv -> data\GSR\28_GSR.csv
Copied: stdata\28\28_PSY.csv -> data\PSY\28_PSY.csv
Copied: stdata\29\29_EEG.csv -> data\EEG\29_EEG.csv
Copied: stdata\29\29_GSR.csv -> data\GSR\29_GSR.csv
Copied: stdata\29\29_PSY.csv -> data\PSY\29_PSY.csv
Copied: stdata\30\30_EEG.csv -> data\EEG\30_EEG.csv
Copied: stdata\30\30_GSR.csv -> data\GSR\30_GSR.csv
Copied: stdata\30\30_PSY.csv -> data\PSY\30_PSY.csv
Copied: stdata\31\31_EEG.csv -> data\EEG\31_EEG.csv
Copied: stdata\31\31_GSR.csv -> data\GSR\31_GSR.csv
Copied: stdata\31\31_PSY.csv -> data\PSY\31_PSY.csv
Copied: stdata\32\32_EEG.csv -> data\EEG\32_EEG.csv
Copied: stdata\32\32_GSR.csv -> data\GSR\32_GSR.csv
Copied: stdata\32\32_PSY.csv -> data\PSY\32_PSY.csv
Copied: stdata\33\33_EEG.csv -> data\EEG\33_EEG.csv
Copied: stdata\33\33_GSR.csv -> data\GSR\33_GSR.csv
Copied: stdata\33\33_PSY.csv -> data\PSY\33_PSY.csv
Copied: stdata\34\34_EEG.csv -> data\EEG\34_EEG.csv
Copied: stdata\34\34_GSR.csv -> data\GSR\34_GSR.csv
Copied: stdata\34\34_PSY.csv -> data\PSY\34_PSY.csv
Copied: stdata\35\35_EEG.csv -> data\EEG\35_EEG.csv
Copied: stdata\35\35_GSR.csv -> data\GSR\35_GSR.csv
Copied: stdata\35\35_PSY.csv -> data\PSY\35_PSY.csv
Copied: stdata\36\36_EEG.csv -> data\EEG\36_EEG.csv
Copied: stdata\36\36_GSR.csv -> data\GSR\36_GSR.csv
Copied: stdata\36\36_PSY.csv -> data\PSY\36_PSY.csv
Copied: stdata\37\37_EEG.csv -> data\EEG\37_EEG.csv
Copied: stdata\37\37_GSR.csv -> data\GSR\37_GSR.csv
Copied: stdata\37\37_PSY.csv -> data\PSY\37_PSY.csv
Copied: stdata\38\38_EEG.csv -> data\EEG\38_EEG.csv
Copied: stdata\38\38_GSR.csv -> data\GSR\38_GSR.csv
Copied: stdata\38\38_PSY.csv -> data\PSY\38_PSY.csv
All done.

In [4]:

# Paths
DATA_ROOT = Path("data")
EEG_PATH = DATA_ROOT / "EEG"
GSR_PATH = DATA_ROOT / "GSR"
PSY_PATH = DATA_ROOT / "PSY"

# Columns to keep
EEG_KEEP = [
    "Delta_TP9","Delta_AF7","Delta_AF8","Delta_TP10",
    "Theta_TP9","Theta_AF7","Theta_AF8","Theta_TP10",
    "Alpha_TP9","Alpha_AF7","Alpha_AF8","Alpha_TP10",
    "Beta_TP9","Beta_AF7","Beta_AF8","Beta_TP10",
    "Gamma_TP9","Gamma_AF7","Gamma_AF8","Gamma_TP10"
]

GSR_KEEP = ["GSR Resistance CAL", "GSR Conductance CAL"]

PSY_KEEP = ["routineStart", "routineEnd", "Difficulty"]

# ---- EEG ----
for i in range(1, 39):
    file = EEG_PATH / f"{i}_EEG.csv"
    if file.exists():
        df = pd.read_csv(file)
        df = df[EEG_KEEP]  # keep only required columns
        df.to_csv(file, index=False)

# ---- GSR ----
for i in range(1, 39):
    file = GSR_PATH / f"{i}_GSR.csv"
    if file.exists():
        df = pd.read_csv(file)
        df = df[GSR_KEEP]
        df.to_csv(file, index=False)

# ---- PSY ----
for i in range(1, 39):
    file = PSY_PATH / f"{i}_PSY.csv"
    if file.exists():
        df = pd.read_csv(file)
        df = df[PSY_KEEP]
        df.to_csv(file, index=False)

print("Columns dropped, only required columns saved back.")

Columns dropped, only required columns saved back.

In [5]:
# Root path
DATA_ROOT = Path("data")

# Folders
EEG_PATH = DATA_ROOT / "EEG"
GSR_PATH = DATA_ROOT / "GSR"
PSY_PATH = DATA_ROOT / "PSY"

# Columns to keep
EEG_KEEP = [
    "Delta_TP9","Delta_AF7","Delta_AF8","Delta_TP10",
    "Theta_TP9","Theta_AF7","Theta_AF8","Theta_TP10",
    "Alpha_TP9","Alpha_AF7","Alpha_AF8","Alpha_TP10",
    "Beta_TP9","Beta_AF7","Beta_AF8","Beta_TP10",
    "Gamma_TP9","Gamma_AF7","Gamma_AF8","Gamma_TP10"
]

GSR_KEEP = ["GSR Resistance CAL", "GSR Conductance CAL"]

PSY_KEEP = ["routineStart", "routineEnd", "Difficulty"]

# ---- EEG ----
for i in range(1, 39):
    file = EEG_PATH / f"{i}_EEG.csv"
    if file.exists():
        df = pd.read_csv(file)
        df = df.loc[:, [col for col in EEG_KEEP if col in df.columns]]
        df.to_csv(file, index=False)
        print(f"Processed {file}")

# ---- GSR ----
for i in range(1, 39):
    file = GSR_PATH / f"{i}_GSR.csv"
    if file.exists():
        df = pd.read_csv(file)
        df = df.loc[:, [col for col in GSR_KEEP if col in df.columns]]
        df.to_csv(file, index=False)
        print(f"Processed {file}")

# ---- PSY ----
for i in range(1, 39):
    file = PSY_PATH / f"{i}_PSY.csv"
    if file.exists():
        df = pd.read_csv(file)
        df = df.loc[:, [col for col in PSY_KEEP if col in df.columns]]
        df.to_csv(file, index=False)
        print(f"Processed {file}")

print("Unrequired columns are dropped from EEG, GSR and PSY")

Unrequired columns are dropped from EEG, GSR and PSY

In [9]:
# Root path
DATA_ROOT = Path("..") / "data"  

# Folders
EEG_PATH = DATA_ROOT / "EEG"
GSR_PATH = DATA_ROOT / "GSR"
PSY_PATH = DATA_ROOT / "PSY"

# Columns to keep
EEG_KEEP = [
    "Delta_TP9","Delta_AF7","Delta_AF8","Delta_TP10",
    "Theta_TP9","Theta_AF7","Theta_AF8","Theta_TP10",
    "Alpha_TP9","Alpha_AF7","Alpha_AF8","Alpha_TP10",
    "Beta_TP9","Beta_AF7","Beta_AF8","Beta_TP10",
    "Gamma_TP9","Gamma_AF7","Gamma_AF8","Gamma_TP10"
]

GSR_KEEP = ["GSR Resistance CAL", "GSR Conductance CAL"]

PSY_KEEP = ["routineStart", "routineEnd", "Difficulty"]

# ---- EEG ----
for i in range(1, 39):
    file = EEG_PATH / f"{i}_EEG.csv"
    if file.exists():
        df = pd.read_csv(file)
        df.columns = df.columns.str.strip()  # remove extra spaces
        df = df[EEG_KEEP]                    # keep only required columns
        df.to_csv(file, index=False)
        print(f"Processed {file}")

# ---- GSR ----
for i in range(1, 39):
    file = GSR_PATH / f"{i}_GSR.csv"
    if file.exists():
        df = pd.read_csv(file)
        df.columns = df.columns.str.strip()
        df = df[GSR_KEEP]
        df.to_csv(file, index=False)
        print(f"Processed {file}")

# ---- PSY ----
for i in range(1, 39):
    file = PSY_PATH / f"{i}_PSY.csv"
    if file.exists():
        df = pd.read_csv(file)
        df.columns = df.columns.str.strip()
        df = df[PSY_KEEP]
        df.to_csv(file, index=False)
        print(f"Processed {file}")

print("All EEG, GSR, PSY files saved (extra columns dropped).")

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\1_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\2_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\3_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\4_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\5_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\6_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\7_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\8_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\9_EEG.csv
Processed ..\data\EEG\10_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\11_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\12_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\13_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\14_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\15_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\16_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\17_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\18_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\19_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\20_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\21_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\22_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\23_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\24_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\25_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\26_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\27_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\28_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\29_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\30_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\31_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\32_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\33_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\34_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\35_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\36_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\37_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\38_EEG.csv
Processed ..\data\GSR\1_GSR.csv
Processed ..\data\GSR\2_GSR.csv
Processed ..\data\GSR\3_GSR.csv
Processed ..\data\GSR\4_GSR.csv
Processed ..\data\GSR\5_GSR.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:36: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\GSR\6_GSR.csv
Processed ..\data\GSR\7_GSR.csv
Processed ..\data\GSR\8_GSR.csv
Processed ..\data\GSR\9_GSR.csv
Processed ..\data\GSR\10_GSR.csv
Processed ..\data\GSR\11_GSR.csv
Processed ..\data\GSR\12_GSR.csv
Processed ..\data\GSR\13_GSR.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:36: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\GSR\14_GSR.csv
Processed ..\data\GSR\15_GSR.csv
Processed ..\data\GSR\16_GSR.csv
Processed ..\data\GSR\17_GSR.csv
Processed ..\data\GSR\18_GSR.csv
Processed ..\data\GSR\19_GSR.csv
Processed ..\data\GSR\20_GSR.csv
Processed ..\data\GSR\21_GSR.csv
Processed ..\data\GSR\22_GSR.csv
Processed ..\data\GSR\23_GSR.csv
Processed ..\data\GSR\24_GSR.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:36: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\GSR\25_GSR.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:36: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\GSR\26_GSR.csv
Processed ..\data\GSR\27_GSR.csv
Processed ..\data\GSR\28_GSR.csv
Processed ..\data\GSR\29_GSR.csv
Processed ..\data\GSR\30_GSR.csv
Processed ..\data\GSR\31_GSR.csv
Processed ..\data\GSR\32_GSR.csv
Processed ..\data\GSR\33_GSR.csv
Processed ..\data\GSR\34_GSR.csv
Processed ..\data\GSR\35_GSR.csv
Processed ..\data\GSR\36_GSR.csv
Processed ..\data\GSR\37_GSR.csv
Processed ..\data\GSR\38_GSR.csv
Processed ..\data\PSY\1_PSY.csv
Processed ..\data\PSY\2_PSY.csv
Processed ..\data\PSY\3_PSY.csv
Processed ..\data\PSY\4_PSY.csv
Processed ..\data\PSY\5_PSY.csv
Processed ..\data\PSY\6_PSY.csv
Processed ..\data\PSY\7_PSY.csv
Processed ..\data\PSY\8_PSY.csv
Processed ..\data\PSY\9_PSY.csv
Processed ..\data\PSY\10_PSY.csv
Processed ..\data\PSY\11_PSY.csv
Processed ..\data\PSY\12_PSY.csv
Processed ..\data\PSY\13_PSY.csv
Processed ..\data\PSY\14_PSY.csv
Processed ..\data\PSY\15_PSY.csv
Processed ..\data\PSY\16_PSY.csv
Processed ..\data\PSY\17_PSY.csv
Processed ..\data\PSY\18_PSY.csv
Processed ..\data\PSY\19_PSY.csv
Processed ..\data\PSY\20_PSY.csv
Processed ..\data\PSY\21_PSY.csv
Processed ..\data\PSY\22_PSY.csv
Processed ..\data\PSY\23_PSY.csv
Processed ..\data\PSY\24_PSY.csv
Processed ..\data\PSY\25_PSY.csv
Processed ..\data\PSY\26_PSY.csv
Processed ..\data\PSY\27_PSY.csv
Processed ..\data\PSY\28_PSY.csv
Processed ..\data\PSY\29_PSY.csv
Processed ..\data\PSY\30_PSY.csv
Processed ..\data\PSY\31_PSY.csv
Processed ..\data\PSY\32_PSY.csv
Processed ..\data\PSY\33_PSY.csv
Processed ..\data\PSY\34_PSY.csv
Processed ..\data\PSY\35_PSY.csv
Processed ..\data\PSY\36_PSY.csv
Processed ..\data\PSY\37_PSY.csv
Processed ..\data\PSY\38_PSY.csv
All EEG, GSR, PSY files saved (extra columns dropped).

In [13]:
folders = {
    "EEG": "../data/EEG",
    "GSR": "../data/GSR",
    "PSY": "../data/PSY"
}

num_files = 38

for folder_name, folder_path in folders.items():
    if not os.path.exists(folder_path):
        print(f"[WARN] Folder not found: {folder_path}")
        continue

    print(f"\n=== Checking folder: {folder_name} ===")

    for i in range(1, num_files + 1):
        file_name = f"{i}_{folder_name}.csv"
        file_path = os.path.join(folder_path, file_name)
        
        if not os.path.exists(file_path):
            print(f"[WARN] File not found: {file_name}")
            continue
        
        try:
            df = pd.read_csv(file_path)
        except Exception as e:
            print(f"Error reading {file_name}: {e}")
            continue
        
        # Count nulls per column
        null_counts = df.isnull().sum().reset_index()
        null_counts.columns = ["Column Name", "Null Count"]
        
        print(f"\n{file_name} -")
        display(null_counts)
        html_table = null_counts.to_html(index=False)

=== Checking folder: EEG ===

1_EEG.csv -

   Column Name  Null Count
0    Delta_TP9          12
1    Delta_AF7          12
2    Delta_AF8          12
3   Delta_TP10          12
4    Theta_TP9          12
5    Theta_AF7          12
6    Theta_AF8          12
7   Theta_TP10          12
8    Alpha_TP9          12
9    Alpha_AF7          12
10   Alpha_AF8          12
11  Alpha_TP10          12
12    Beta_TP9          12
13    Beta_AF7          12
14    Beta_AF8          12
15   Beta_TP10          12
16   Gamma_TP9          12
17   Gamma_AF7          12
18   Gamma_AF8          12
19  Gamma_TP10          12

2_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         209
1    Delta_AF7         209
2    Delta_AF8         209
3   Delta_TP10         209
4    Theta_TP9         209
5    Theta_AF7         209
6    Theta_AF8         209
7   Theta_TP10         209
8    Alpha_TP9         209
9    Alpha_AF7         209
10   Alpha_AF8         209
11  Alpha_TP10         209
12    Beta_TP9         209
13    Beta_AF7         209
14    Beta_AF8         209
15   Beta_TP10         209
16   Gamma_TP9         209
17   Gamma_AF7         209
18   Gamma_AF8         209
19  Gamma_TP10         209

3_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         318
1    Delta_AF7         318
2    Delta_AF8         318
3   Delta_TP10         318
4    Theta_TP9         318
5    Theta_AF7         318
6    Theta_AF8         318
7   Theta_TP10         318
8    Alpha_TP9         318
9    Alpha_AF7         318
10   Alpha_AF8         318
11  Alpha_TP10         318
12    Beta_TP9         318
13    Beta_AF7         318
14    Beta_AF8         318
15   Beta_TP10         318
16   Gamma_TP9         318
17   Gamma_AF7         318
18   Gamma_AF8         318
19  Gamma_TP10         318

4_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         142
1    Delta_AF7         142
2    Delta_AF8         142
3   Delta_TP10         142
4    Theta_TP9         142
5    Theta_AF7         142
6    Theta_AF8         142
7   Theta_TP10         142
8    Alpha_TP9         142
9    Alpha_AF7         142
10   Alpha_AF8         142
11  Alpha_TP10         142
12    Beta_TP9         142
13    Beta_AF7         142
14    Beta_AF8         142
15   Beta_TP10         142
16   Gamma_TP9         142
17   Gamma_AF7         142
18   Gamma_AF8         142
19  Gamma_TP10         142

5_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         579
1    Delta_AF7         579
2    Delta_AF8         579
3   Delta_TP10         579
4    Theta_TP9         579
5    Theta_AF7         579
6    Theta_AF8         579
7   Theta_TP10         579
8    Alpha_TP9         579
9    Alpha_AF7         579
10   Alpha_AF8         579
11  Alpha_TP10         579
12    Beta_TP9         579
13    Beta_AF7         579
14    Beta_AF8         579
15   Beta_TP10         579
16   Gamma_TP9         579
17   Gamma_AF7         579
18   Gamma_AF8         579
19  Gamma_TP10         579

6_EEG.csv -

   Column Name  Null Count
0    Delta_TP9          64
1    Delta_AF7          64
2    Delta_AF8          64
3   Delta_TP10          64
4    Theta_TP9          64
5    Theta_AF7          64
6    Theta_AF8          64
7   Theta_TP10          64
8    Alpha_TP9          64
9    Alpha_AF7          64
10   Alpha_AF8          64
11  Alpha_TP10          64
12    Beta_TP9          64
13    Beta_AF7          64
14    Beta_AF8          64
15   Beta_TP10          64
16   Gamma_TP9          64
17   Gamma_AF7          64
18   Gamma_AF8          64
19  Gamma_TP10          64

7_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         438
1    Delta_AF7         438
2    Delta_AF8         438
3   Delta_TP10         438
4    Theta_TP9         438
5    Theta_AF7         438
6    Theta_AF8         438
7   Theta_TP10         438
8    Alpha_TP9         438
9    Alpha_AF7         438
10   Alpha_AF8         438
11  Alpha_TP10         438
12    Beta_TP9         438
13    Beta_AF7         438
14    Beta_AF8         438
15   Beta_TP10         438
16   Gamma_TP9         438
17   Gamma_AF7         438
18   Gamma_AF8         438
19  Gamma_TP10         438

8_EEG.csv -

   Column Name  Null Count
0    Delta_TP9          82
1    Delta_AF7          82
2    Delta_AF8          82
3   Delta_TP10          82
4    Theta_TP9          82
5    Theta_AF7          82
6    Theta_AF8          82
7   Theta_TP10          82
8    Alpha_TP9          82
9    Alpha_AF7          82
10   Alpha_AF8          82
11  Alpha_TP10          82
12    Beta_TP9          82
13    Beta_AF7          82
14    Beta_AF8          82
15   Beta_TP10          82
16   Gamma_TP9          82
17   Gamma_AF7          82
18   Gamma_AF8          82
19  Gamma_TP10          82

9_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         392
1    Delta_AF7         392
2    Delta_AF8         392
3   Delta_TP10         392
4    Theta_TP9         392
5    Theta_AF7         392
6    Theta_AF8         392
7   Theta_TP10         392
8    Alpha_TP9         392
9    Alpha_AF7         392
10   Alpha_AF8         392
11  Alpha_TP10         392
12    Beta_TP9         392
13    Beta_AF7         392
14    Beta_AF8         392
15   Beta_TP10         392
16   Gamma_TP9         392
17   Gamma_AF7         392
18   Gamma_AF8         392
19  Gamma_TP10         392

10_EEG.csv -

   Column Name  Null Count
0    Delta_TP9           0
1    Delta_AF7           0
2    Delta_AF8           0
3   Delta_TP10           0
4    Theta_TP9           0
5    Theta_AF7           0
6    Theta_AF8           0
7   Theta_TP10           0
8    Alpha_TP9           0
9    Alpha_AF7           0
10   Alpha_AF8           0
11  Alpha_TP10           0
12    Beta_TP9           0
13    Beta_AF7           0
14    Beta_AF8           0
15   Beta_TP10           0
16   Gamma_TP9           0
17   Gamma_AF7           0
18   Gamma_AF8           0
19  Gamma_TP10           0

11_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         217
1    Delta_AF7         217
2    Delta_AF8         217
3   Delta_TP10         217
4    Theta_TP9         217
5    Theta_AF7         217
6    Theta_AF8         217
7   Theta_TP10         217
8    Alpha_TP9         217
9    Alpha_AF7         217
10   Alpha_AF8         217
11  Alpha_TP10         217
12    Beta_TP9         217
13    Beta_AF7         217
14    Beta_AF8         217
15   Beta_TP10         217
16   Gamma_TP9         217
17   Gamma_AF7         217
18   Gamma_AF8         217
19  Gamma_TP10         217

12_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         603
1    Delta_AF7         603
2    Delta_AF8         603
3   Delta_TP10         603
4    Theta_TP9         603
5    Theta_AF7         603
6    Theta_AF8         603
7   Theta_TP10         603
8    Alpha_TP9         603
9    Alpha_AF7         603
10   Alpha_AF8         603
11  Alpha_TP10         603
12    Beta_TP9         603
13    Beta_AF7         603
14    Beta_AF8         603
15   Beta_TP10         603
16   Gamma_TP9         603
17   Gamma_AF7         603
18   Gamma_AF8         603
19  Gamma_TP10         603

13_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         383
1    Delta_AF7         383
2    Delta_AF8         383
3   Delta_TP10         383
4    Theta_TP9         383
5    Theta_AF7         383
6    Theta_AF8         383
7   Theta_TP10         383
8    Alpha_TP9         383
9    Alpha_AF7         383
10   Alpha_AF8         383
11  Alpha_TP10         383
12    Beta_TP9         383
13    Beta_AF7         383
14    Beta_AF8         383
15   Beta_TP10         383
16   Gamma_TP9         383
17   Gamma_AF7         383
18   Gamma_AF8         383
19  Gamma_TP10         383

14_EEG.csv -

   Column Name  Null Count
0    Delta_TP9          56
1    Delta_AF7          56
2    Delta_AF8          56
3   Delta_TP10          56
4    Theta_TP9          56
5    Theta_AF7          56
6    Theta_AF8          56
7   Theta_TP10          56
8    Alpha_TP9          56
9    Alpha_AF7          56
10   Alpha_AF8          56
11  Alpha_TP10          56
12    Beta_TP9          56
13    Beta_AF7          56
14    Beta_AF8          56
15   Beta_TP10          56
16   Gamma_TP9          56
17   Gamma_AF7          56
18   Gamma_AF8          56
19  Gamma_TP10          56

15_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         182
1    Delta_AF7         182
2    Delta_AF8         182
3   Delta_TP10         182
4    Theta_TP9         182
5    Theta_AF7         182
6    Theta_AF8         182
7   Theta_TP10         182
8    Alpha_TP9         182
9    Alpha_AF7         182
10   Alpha_AF8         182
11  Alpha_TP10         182
12    Beta_TP9         182
13    Beta_AF7         182
14    Beta_AF8         182
15   Beta_TP10         182
16   Gamma_TP9         182
17   Gamma_AF7         182
18   Gamma_AF8         182
19  Gamma_TP10         182

16_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         191
1    Delta_AF7         191
2    Delta_AF8         191
3   Delta_TP10         191
4    Theta_TP9         191
5    Theta_AF7         191
6    Theta_AF8         191
7   Theta_TP10         191
8    Alpha_TP9         191
9    Alpha_AF7         191
10   Alpha_AF8         191
11  Alpha_TP10         191
12    Beta_TP9         191
13    Beta_AF7         191
14    Beta_AF8         191
15   Beta_TP10         191
16   Gamma_TP9         191
17   Gamma_AF7         191
18   Gamma_AF8         191
19  Gamma_TP10         191

17_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         238
1    Delta_AF7         238
2    Delta_AF8         238
3   Delta_TP10         238
4    Theta_TP9         238
5    Theta_AF7         238
6    Theta_AF8         238
7   Theta_TP10         238
8    Alpha_TP9         238
9    Alpha_AF7         238
10   Alpha_AF8         238
11  Alpha_TP10         238
12    Beta_TP9         238
13    Beta_AF7         238
14    Beta_AF8         238
15   Beta_TP10         238
16   Gamma_TP9         238
17   Gamma_AF7         238
18   Gamma_AF8         238
19  Gamma_TP10         238

18_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         443
1    Delta_AF7         443
2    Delta_AF8         443
3   Delta_TP10         443
4    Theta_TP9         443
5    Theta_AF7         443
6    Theta_AF8         443
7   Theta_TP10         443
8    Alpha_TP9         443
9    Alpha_AF7         443
10   Alpha_AF8         443
11  Alpha_TP10         443
12    Beta_TP9         443
13    Beta_AF7         443
14    Beta_AF8         443
15   Beta_TP10         443
16   Gamma_TP9         443
17   Gamma_AF7         443
18   Gamma_AF8         443
19  Gamma_TP10         443

19_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         228
1    Delta_AF7         228
2    Delta_AF8         228
3   Delta_TP10         228
4    Theta_TP9         228
5    Theta_AF7         228
6    Theta_AF8         228
7   Theta_TP10         228
8    Alpha_TP9         228
9    Alpha_AF7         228
10   Alpha_AF8         228
11  Alpha_TP10         228
12    Beta_TP9         228
13    Beta_AF7         228
14    Beta_AF8         228
15   Beta_TP10         228
16   Gamma_TP9         228
17   Gamma_AF7         228
18   Gamma_AF8         228
19  Gamma_TP10         228

20_EEG.csv -

   Column Name  Null Count
0    Delta_TP9          42
1    Delta_AF7          42
2    Delta_AF8          42
3   Delta_TP10          42
4    Theta_TP9          42
5    Theta_AF7          42
6    Theta_AF8          42
7   Theta_TP10          42
8    Alpha_TP9          42
9    Alpha_AF7          42
10   Alpha_AF8          42
11  Alpha_TP10          42
12    Beta_TP9          42
13    Beta_AF7          42
14    Beta_AF8          42
15   Beta_TP10          42
16   Gamma_TP9          42
17   Gamma_AF7          42
18   Gamma_AF8          42
19  Gamma_TP10          42

21_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         221
1    Delta_AF7         221
2    Delta_AF8         221
3   Delta_TP10         221
4    Theta_TP9         221
5    Theta_AF7         221
6    Theta_AF8         221
7   Theta_TP10         221
8    Alpha_TP9         221
9    Alpha_AF7         221
10   Alpha_AF8         221
11  Alpha_TP10         221
12    Beta_TP9         221
13    Beta_AF7         221
14    Beta_AF8         221
15   Beta_TP10         221
16   Gamma_TP9         221
17   Gamma_AF7         221
18   Gamma_AF8         221
19  Gamma_TP10         221

22_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         312
1    Delta_AF7         312
2    Delta_AF8         312
3   Delta_TP10         312
4    Theta_TP9         312
5    Theta_AF7         312
6    Theta_AF8         312
7   Theta_TP10         312
8    Alpha_TP9         312
9    Alpha_AF7         312
10   Alpha_AF8         312
11  Alpha_TP10         312
12    Beta_TP9         312
13    Beta_AF7         312
14    Beta_AF8         312
15   Beta_TP10         312
16   Gamma_TP9         312
17   Gamma_AF7         312
18   Gamma_AF8         312
19  Gamma_TP10         312

23_EEG.csv -

   Column Name  Null Count
0    Delta_TP9        1161
1    Delta_AF7        1161
2    Delta_AF8        1161
3   Delta_TP10        1161
4    Theta_TP9        1161
5    Theta_AF7        1161
6    Theta_AF8        1161
7   Theta_TP10        1161
8    Alpha_TP9        1161
9    Alpha_AF7        1161
10   Alpha_AF8        1161
11  Alpha_TP10        1161
12    Beta_TP9        1161
13    Beta_AF7        1161
14    Beta_AF8        1161
15   Beta_TP10        1161
16   Gamma_TP9        1161
17   Gamma_AF7        1161
18   Gamma_AF8        1161
19  Gamma_TP10        1161

24_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         167
1    Delta_AF7         167
2    Delta_AF8         167
3   Delta_TP10         167
4    Theta_TP9         167
5    Theta_AF7         167
6    Theta_AF8         167
7   Theta_TP10         167
8    Alpha_TP9         167
9    Alpha_AF7         167
10   Alpha_AF8         167
11  Alpha_TP10         167
12    Beta_TP9         167
13    Beta_AF7         167
14    Beta_AF8         167
15   Beta_TP10         167
16   Gamma_TP9         167
17   Gamma_AF7         167
18   Gamma_AF8         167
19  Gamma_TP10         167

25_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         609
1    Delta_AF7         609
2    Delta_AF8         609
3   Delta_TP10         609
4    Theta_TP9         609
5    Theta_AF7         609
6    Theta_AF8         609
7   Theta_TP10         609
8    Alpha_TP9         609
9    Alpha_AF7         609
10   Alpha_AF8         609
11  Alpha_TP10         609
12    Beta_TP9         609
13    Beta_AF7         609
14    Beta_AF8         609
15   Beta_TP10         609
16   Gamma_TP9         609
17   Gamma_AF7         609
18   Gamma_AF8         609
19  Gamma_TP10         609

26_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         155
1    Delta_AF7         155
2    Delta_AF8         155
3   Delta_TP10         155
4    Theta_TP9         155
5    Theta_AF7         155
6    Theta_AF8         155
7   Theta_TP10         155
8    Alpha_TP9         155
9    Alpha_AF7         155
10   Alpha_AF8         155
11  Alpha_TP10         155
12    Beta_TP9         155
13    Beta_AF7         155
14    Beta_AF8         155
15   Beta_TP10         155
16   Gamma_TP9         155
17   Gamma_AF7         155
18   Gamma_AF8         155
19  Gamma_TP10         155

27_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         187
1    Delta_AF7         187
2    Delta_AF8         187
3   Delta_TP10         187
4    Theta_TP9         187
5    Theta_AF7         187
6    Theta_AF8         187
7   Theta_TP10         187
8    Alpha_TP9         187
9    Alpha_AF7         187
10   Alpha_AF8         187
11  Alpha_TP10         187
12    Beta_TP9         187
13    Beta_AF7         187
14    Beta_AF8         187
15   Beta_TP10         187
16   Gamma_TP9         187
17   Gamma_AF7         187
18   Gamma_AF8         187
19  Gamma_TP10         187

28_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         153
1    Delta_AF7         153
2    Delta_AF8         153
3   Delta_TP10         153
4    Theta_TP9         153
5    Theta_AF7         153
6    Theta_AF8         153
7   Theta_TP10         153
8    Alpha_TP9         153
9    Alpha_AF7         153
10   Alpha_AF8         153
11  Alpha_TP10         153
12    Beta_TP9         153
13    Beta_AF7         153
14    Beta_AF8         153
15   Beta_TP10         153
16   Gamma_TP9         153
17   Gamma_AF7         153
18   Gamma_AF8         153
19  Gamma_TP10         153

29_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         656
1    Delta_AF7         656
2    Delta_AF8         656
3   Delta_TP10         656
4    Theta_TP9         656
5    Theta_AF7         656
6    Theta_AF8         656
7   Theta_TP10         656
8    Alpha_TP9         656
9    Alpha_AF7         656
10   Alpha_AF8         656
11  Alpha_TP10         656
12    Beta_TP9         656
13    Beta_AF7         656
14    Beta_AF8         656
15   Beta_TP10         656
16   Gamma_TP9         656
17   Gamma_AF7         656
18   Gamma_AF8         656
19  Gamma_TP10         656

30_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         314
1    Delta_AF7         314
2    Delta_AF8         314
3   Delta_TP10         314
4    Theta_TP9         314
5    Theta_AF7         314
6    Theta_AF8         314
7   Theta_TP10         314
8    Alpha_TP9         314
9    Alpha_AF7         314
10   Alpha_AF8         314
11  Alpha_TP10         314
12    Beta_TP9         314
13    Beta_AF7         314
14    Beta_AF8         314
15   Beta_TP10         314
16   Gamma_TP9         314
17   Gamma_AF7         314
18   Gamma_AF8         314
19  Gamma_TP10         314

31_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         138
1    Delta_AF7         138
2    Delta_AF8         138
3   Delta_TP10         138
4    Theta_TP9         138
5    Theta_AF7         138
6    Theta_AF8         138
7   Theta_TP10         138
8    Alpha_TP9         138
9    Alpha_AF7         138
10   Alpha_AF8         138
11  Alpha_TP10         138
12    Beta_TP9         138
13    Beta_AF7         138
14    Beta_AF8         138
15   Beta_TP10         138
16   Gamma_TP9         138
17   Gamma_AF7         138
18   Gamma_AF8         138
19  Gamma_TP10         138

32_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         600
1    Delta_AF7         600
2    Delta_AF8         600
3   Delta_TP10         600
4    Theta_TP9         600
5    Theta_AF7         600
6    Theta_AF8         600
7   Theta_TP10         600
8    Alpha_TP9         600
9    Alpha_AF7         600
10   Alpha_AF8         600
11  Alpha_TP10         600
12    Beta_TP9         600
13    Beta_AF7         600
14    Beta_AF8         600
15   Beta_TP10         600
16   Gamma_TP9         600
17   Gamma_AF7         600
18   Gamma_AF8         600
19  Gamma_TP10         600

33_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         623
1    Delta_AF7         623
2    Delta_AF8         623
3   Delta_TP10         623
4    Theta_TP9         623
5    Theta_AF7         623
6    Theta_AF8         623
7   Theta_TP10         623
8    Alpha_TP9         623
9    Alpha_AF7         623
10   Alpha_AF8         623
11  Alpha_TP10         623
12    Beta_TP9         623
13    Beta_AF7         623
14    Beta_AF8         623
15   Beta_TP10         623
16   Gamma_TP9         623
17   Gamma_AF7         623
18   Gamma_AF8         623
19  Gamma_TP10         623

34_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         275
1    Delta_AF7         275
2    Delta_AF8         275
3   Delta_TP10         275
4    Theta_TP9         275
5    Theta_AF7         275
6    Theta_AF8         275
7   Theta_TP10         275
8    Alpha_TP9         275
9    Alpha_AF7         275
10   Alpha_AF8         275
11  Alpha_TP10         275
12    Beta_TP9         275
13    Beta_AF7         275
14    Beta_AF8         275
15   Beta_TP10         275
16   Gamma_TP9         275
17   Gamma_AF7         275
18   Gamma_AF8         275
19  Gamma_TP10         275

35_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         735
1    Delta_AF7         735
2    Delta_AF8         735
3   Delta_TP10         735
4    Theta_TP9         735
5    Theta_AF7         735
6    Theta_AF8         735
7   Theta_TP10         735
8    Alpha_TP9         735
9    Alpha_AF7         735
10   Alpha_AF8         735
11  Alpha_TP10         735
12    Beta_TP9         735
13    Beta_AF7         735
14    Beta_AF8         735
15   Beta_TP10         735
16   Gamma_TP9         735
17   Gamma_AF7         735
18   Gamma_AF8         735
19  Gamma_TP10         735

36_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         247
1    Delta_AF7         247
2    Delta_AF8         247
3   Delta_TP10         247
4    Theta_TP9         247
5    Theta_AF7         247
6    Theta_AF8         247
7   Theta_TP10         247
8    Alpha_TP9         247
9    Alpha_AF7         247
10   Alpha_AF8         247
11  Alpha_TP10         247
12    Beta_TP9         247
13    Beta_AF7         247
14    Beta_AF8         247
15   Beta_TP10         247
16   Gamma_TP9         247
17   Gamma_AF7         247
18   Gamma_AF8         247
19  Gamma_TP10         247

37_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         345
1    Delta_AF7         345
2    Delta_AF8         345
3   Delta_TP10         345
4    Theta_TP9         345
5    Theta_AF7         345
6    Theta_AF8         345
7   Theta_TP10         345
8    Alpha_TP9         345
9    Alpha_AF7         345
10   Alpha_AF8         345
11  Alpha_TP10         345
12    Beta_TP9         345
13    Beta_AF7         345
14    Beta_AF8         345
15   Beta_TP10         345
16   Gamma_TP9         345
17   Gamma_AF7         345
18   Gamma_AF8         345
19  Gamma_TP10         345

38_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         280
1    Delta_AF7         280
2    Delta_AF8         280
3   Delta_TP10         280
4    Theta_TP9         280
5    Theta_AF7         280
6    Theta_AF8         280
7   Theta_TP10         280
8    Alpha_TP9         280
9    Alpha_AF7         280
10   Alpha_AF8         280
11  Alpha_TP10         280
12    Beta_TP9         280
13    Beta_AF7         280
14    Beta_AF8         280
15   Beta_TP10         280
16   Gamma_TP9         280
17   Gamma_AF7         280
18   Gamma_AF8         280
19  Gamma_TP10         280

=== Checking folder: GSR ===

1_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

2_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

3_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

4_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

5_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

6_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

7_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

8_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

9_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

10_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

11_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

12_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

13_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

14_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

15_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

16_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

17_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

18_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

19_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

20_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

21_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

22_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

23_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

24_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

25_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

26_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

27_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

28_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

29_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

30_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

31_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

32_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

33_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

34_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

35_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

36_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

37_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

38_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

=== Checking folder: PSY ===

1_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

2_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

3_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

4_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

5_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           0

6_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           2

7_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

8_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

9_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

10_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

11_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           0

12_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           0

13_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           2

14_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

15_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

16_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           0

17_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

18_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           0

19_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           2

20_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

21_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

22_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

23_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

24_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

25_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

26_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

27_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

28_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

29_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

30_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

31_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

32_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

33_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           2

34_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           0

35_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

36_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           2

37_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

38_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           2

In [14]:
folders = {
    "EEG": "../data/EEG",
    "GSR": "../data/GSR",
    "PSY": "../data/PSY"
}

num_files = 38

for folder_name, folder_path in folders.items():
    if not os.path.exists(folder_path):
        print(f"[WARN] Folder not found: {folder_path}")
        continue

    print(f"\n=== Processing folder: {folder_name} ===")

    for i in range(1, num_files + 1):
        file_name = f"{i}_{folder_name}.csv"
        file_path = os.path.join(folder_path, file_name)
        
        if not os.path.exists(file_path):
            print(f"[WARN] File not found: {file_name}")
            continue
        
        df = pd.read_csv(file_path)
        
        if folder_name == "EEG":
            # Fill all EEG columns with mean
            df.fillna(df.mean(), inplace=True)
        
        elif folder_name == "GSR":
            # Fill GSR columns with linear interpolation
            df.interpolate(method='linear', inplace=True)
            df.fillna(df.mean(), inplace=True)  # in case first/last rows are NaN
        
        elif folder_name == "PSY":
            # Fill timestamps with forward fill, Difficulty with median
            for col in df.columns:
                if df[col].dtype == 'object':
                    df[col].fillna(method='ffill', inplace=True)
                else:
                    df[col].fillna(df[col].median(), inplace=True)
        
        # Save the cleaned file
        df.to_csv(file_path, index=False)
        print(f"{file_name} cleaned and saved.")

=== Processing folder: EEG ===
1_EEG.csv cleaned and saved.
2_EEG.csv cleaned and saved.
3_EEG.csv cleaned and saved.
4_EEG.csv cleaned and saved.
5_EEG.csv cleaned and saved.
6_EEG.csv cleaned and saved.
7_EEG.csv cleaned and saved.
8_EEG.csv cleaned and saved.
9_EEG.csv cleaned and saved.
10_EEG.csv cleaned and saved.
11_EEG.csv cleaned and saved.
12_EEG.csv cleaned and saved.
13_EEG.csv cleaned and saved.
14_EEG.csv cleaned and saved.
15_EEG.csv cleaned and saved.
16_EEG.csv cleaned and saved.
17_EEG.csv cleaned and saved.
18_EEG.csv cleaned and saved.
19_EEG.csv cleaned and saved.
20_EEG.csv cleaned and saved.
21_EEG.csv cleaned and saved.
22_EEG.csv cleaned and saved.
23_EEG.csv cleaned and saved.
24_EEG.csv cleaned and saved.
25_EEG.csv cleaned and saved.
26_EEG.csv cleaned and saved.
27_EEG.csv cleaned and saved.
28_EEG.csv cleaned and saved.
29_EEG.csv cleaned and saved.
30_EEG.csv cleaned and saved.
31_EEG.csv cleaned and saved.
32_EEG.csv cleaned and saved.
33_EEG.csv cleaned and saved.
34_EEG.csv cleaned and saved.
35_EEG.csv cleaned and saved.
36_EEG.csv cleaned and saved.
37_EEG.csv cleaned and saved.
38_EEG.csv cleaned and saved.

=== Processing folder: GSR ===
1_GSR.csv cleaned and saved.
2_GSR.csv cleaned and saved.
3_GSR.csv cleaned and saved.
4_GSR.csv cleaned and saved.
5_GSR.csv cleaned and saved.
6_GSR.csv cleaned and saved.
7_GSR.csv cleaned and saved.
8_GSR.csv cleaned and saved.
9_GSR.csv cleaned and saved.
10_GSR.csv cleaned and saved.
11_GSR.csv cleaned and saved.
12_GSR.csv cleaned and saved.
13_GSR.csv cleaned and saved.
14_GSR.csv cleaned and saved.
15_GSR.csv cleaned and saved.
16_GSR.csv cleaned and saved.
17_GSR.csv cleaned and saved.
18_GSR.csv cleaned and saved.
19_GSR.csv cleaned and saved.
20_GSR.csv cleaned and saved.
21_GSR.csv cleaned and saved.
22_GSR.csv cleaned and saved.
23_GSR.csv cleaned and saved.
24_GSR.csv cleaned and saved.
25_GSR.csv cleaned and saved.
26_GSR.csv cleaned and saved.
27_GSR.csv cleaned and saved.
28_GSR.csv cleaned and saved.
29_GSR.csv cleaned and saved.
30_GSR.csv cleaned and saved.
31_GSR.csv cleaned and saved.
32_GSR.csv cleaned and saved.
33_GSR.csv cleaned and saved.
34_GSR.csv cleaned and saved.
35_GSR.csv cleaned and saved.
36_GSR.csv cleaned and saved.
37_GSR.csv cleaned and saved.
38_GSR.csv cleaned and saved.

=== Processing folder: PSY ===
1_PSY.csv cleaned and saved.
2_PSY.csv cleaned and saved.
3_PSY.csv cleaned and saved.

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)

4_PSY.csv cleaned and saved.
5_PSY.csv cleaned and saved.
6_PSY.csv cleaned and saved.
7_PSY.csv cleaned and saved.
8_PSY.csv cleaned and saved.
9_PSY.csv cleaned and saved.
10_PSY.csv cleaned and saved.
11_PSY.csv cleaned and saved.
12_PSY.csv cleaned and saved.
13_PSY.csv cleaned and saved.
14_PSY.csv cleaned and saved.
15_PSY.csv cleaned and saved.

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.


16_PSY.csv cleaned and saved.
17_PSY.csv cleaned and saved.
18_PSY.csv cleaned and saved.
19_PSY.csv cleaned and saved.
20_PSY.csv cleaned and saved.
21_PSY.csv cleaned and saved.
22_PSY.csv cleaned and saved.
23_PSY.csv cleaned and saved.
24_PSY.csv cleaned and saved.
25_PSY.csv cleaned and saved.
26_PSY.csv cleaned and saved.
27_PSY.csv cleaned and saved.
28_PSY.csv cleaned and saved.
29_PSY.csv cleaned and saved.
30_PSY.csv cleaned and saved.

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.


31_PSY.csv cleaned and saved.
32_PSY.csv cleaned and saved.
33_PSY.csv cleaned and saved.
34_PSY.csv cleaned and saved.
35_PSY.csv cleaned and saved.
36_PSY.csv cleaned and saved.
37_PSY.csv cleaned and saved.
38_PSY.csv cleaned and saved.

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(method='ffill', inplace=True)
C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1530918519.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col].fillna(method='ffill', inplace=True)

In [22]:
eeg_path = "../data/EEG"
gsr_path = "../data/GSR"
psy_path = "../data/PSY"
num_files = 38

# Initialize master dataset
all_trials = []

for i in range(1, num_files + 1):
    print(f"Processing participant {i}...")

    # Load data
    eeg_file = os.path.join(eeg_path, f"{i}_EEG.csv")
    gsr_file = os.path.join(gsr_path, f"{i}_GSR.csv")
    psy_file = os.path.join(psy_path, f"{i}_PSY.csv")
    
    if not (os.path.exists(eeg_file) and os.path.exists(gsr_file) and os.path.exists(psy_file)):
        print(f"[WARN] Missing files for participant {i}, skipping.")
        continue
    
    eeg_df = pd.read_csv(eeg_file)
    gsr_df = pd.read_csv(gsr_file)
    psy_df = pd.read_csv(psy_file)
    
    # Drop empty columns if any
    eeg_df.dropna(how='all', inplace=True)
    gsr_df.dropna(how='all', inplace=True)
    
    # Total duration of the session
    session_start = psy_df['routineStart'].min()
    session_end   = psy_df['routineEnd'].max()
    total_duration = session_end - session_start
    
    n_eeg = len(eeg_df)
    n_gsr = len(gsr_df)
    
    # Loop over each trial in PSY
    for idx, trial in psy_df.iterrows():
        trial_start = trial['routineStart']
        trial_end   = trial['routineEnd']
        label = trial['Difficulty']  # Map to binary or 3-class if needed

        # Map PSY trial to EEG rows proportionally
        start_idx_eeg = int((trial_start - session_start) / total_duration * n_eeg)
        end_idx_eeg   = int((trial_end - session_start) / total_duration * n_eeg)
        eeg_trial = eeg_df.iloc[start_idx_eeg:end_idx_eeg]
        
        # Map PSY trial to GSR rows proportionally
        start_idx_gsr = int((trial_start - session_start) / total_duration * n_gsr)
        end_idx_gsr   = int((trial_end - session_start) / total_duration * n_gsr)
        gsr_trial = gsr_df.iloc[start_idx_gsr:end_idx_gsr]
        
        # Skip trial if no data
        if eeg_trial.empty or gsr_trial.empty:
            continue
        
        features = {}
        
        # Aggregate EEG features
        for col in eeg_trial.columns:
            features[f"{col}_mean"] = eeg_trial[col].mean()
            features[f"{col}_std"] = eeg_trial[col].std()
            features[f"{col}_min"] = eeg_trial[col].min()
            features[f"{col}_max"] = eeg_trial[col].max()
            features[f"{col}_median"] = eeg_trial[col].median()
        
        # Aggregate GSR features
        for col in gsr_trial.columns:
            features[f"{col}_mean"] = gsr_trial[col].mean()
            features[f"{col}_std"] = gsr_trial[col].std()
            features[f"{col}_min"] = gsr_trial[col].min()
            features[f"{col}_max"] = gsr_trial[col].max()
            features[f"{col}_median"] = gsr_trial[col].median()
        
        # Add participant, trial, and label
        features['participant'] = i
        features['trial'] = idx + 1
        features['label'] = label
        
        all_trials.append(features)

# Create master DataFrame
master_df = pd.DataFrame(all_trials)

# Fill any remaining NaNs with 0
master_df.fillna(0, inplace=True)

output_file = os.path.join("data", "per_trial_dataset.csv")
master_df.to_csv(output_file, index=False)
print(f"Per-trial dataset created: {output_file}")

Processing participant 1...

TypeError: Could not convert string '2023-03-28 17:03:16.7732023-03-28 17:03:16.7762023-03-28 17:03:16.7782023-03-28 17:03:16.7982023-03-28 17:03:16.8012023-03-28 17:03:16.8032023-03-28 17:03:16.8052023-03-28 17:03:16.8072023-03-28 17:03:16.7832023-03-28 17:03:16.8122023-03-28 17:03:16.8152023-03-28 17:03:16.8172023-03-28 17:03:16.8192023-03-28 17:03:16.8212023-03-28 17:03:16.8242023-03-28 17:03:16.8262023-03-28 17:03:16.8282023-03-28 17:03:16.8312023-03-28 17:03:16.8332023-03-28 17:03:16.8362023-03-28 17:03:16.8382023-03-28 17:03:16.8402023-03-28 17:03:16.8422023-03-28 17:03:16.8452023-03-28 17:03:16.8472023-03-28 17:03:16.8492023-03-28 17:03:16.8512023-03-28 17:03:16.8542023-03-28 17:03:16.8562023-03-28 17:03:16.9092023-03-28 17:03:16.9112023-03-28 17:03:16.9142023-03-28 17:03:16.9172023-03-28 17:03:16.9192023-03-28 17:03:16.9282023-03-28 17:03:16.9302023-03-28 17:03:16.9312023-03-28 17:03:16.9332023-03-28 17:03:16.9342023-03-28 17:03:16.9202023-03-28 17:03:16.9372023-03-28 17:03:16.9382023-03-28 17:03:16.9402023-03-28 17:03:16.9412023-03-28 17:03:16.9432023-03-28 17:03:16.9442023-03-28 17:03:16.9472023-03-28 17:03:16.9482023-03-28 17:03:16.9502023-03-28 17:03:16.9512023-03-28 17:03:16.9532023-03-28 17:03:16.9542023-03-28 17:03:16.9562023-03-28 17:03:16.9572023-03-28 17:03:16.9612023-03-28 17:03:16.9642023-03-28 17:03:16.9662023-03-28 17:03:16.9672023-03-28 17:03:16.9702023-03-28 17:03:16.9712023-03-28 17:03:16.9732023-03-28 17:03:16.9742023-03-28 17:03:16.9762023-03-28 17:03:16.9772023-03-28 17:03:16.9792023-03-28 17:03:16.9902023-03-28 17:03:16.9922023-03-28 17:03:16.9932023-03-28 17:03:16.9962023-03-28 17:03:16.9982023-03-28 17:03:16.9812023-03-28 17:03:17.0012023-03-28 17:03:17.0022023-03-28 17:03:17.0032023-03-28 17:03:17.0052023-03-28 17:03:17.0072023-03-28 17:03:17.0082023-03-28 17:03:17.0102023-03-28 17:03:17.0112023-03-28 17:03:17.0132023-03-28 17:03:17.0142023-03-28 17:03:17.0152023-03-28 17:03:17.0172023-03-28 17:03:17.0182023-03-28 17:03:17.0192023-03-28 17:03:17.0212023-03-28 17:03:17.0222023-03-28 17:03:17.0232023-03-28 17:03:17.0242023-03-28 17:03:17.0262023-03-28 17:03:17.0272023-03-28 17:03:17.0282023-03-28 17:03:17.0292023-03-28 17:03:17.0302023-03-28 17:03:17.0322023-03-28 17:03:17.0332023-03-28 17:03:17.0422023-03-28 17:03:17.0432023-03-28 17:03:17.0452023-03-28 17:03:17.0462023-03-28 17:03:17.0472023-03-28 17:03:17.0342023-03-28 17:03:17.0502023-03-28 17:03:17.0512023-03-28 17:03:17.0792023-03-28 17:03:17.0812023-03-28 17:03:17.0822023-03-28 17:03:17.0832023-03-28 17:03:17.0842023-03-28 17:03:17.0862023-03-28 17:03:17.0872023-03-28 17:03:17.0882023-03-28 17:03:17.0892023-03-28 17:03:17.0902023-03-28 17:03:17.0912023-03-28 17:03:17.0922023-03-28 17:03:17.0942023-03-28 17:03:17.0952023-03-28 17:03:17.0962023-03-28 17:03:17.0972023-03-28 17:03:17.0992023-03-28 17:03:17.1002023-03-28 17:03:17.1022023-03-28 17:03:17.1032023-03-28 17:03:17.1042023-03-28 17:03:17.1062023-03-28 17:03:17.1072023-03-28 17:03:17.1162023-03-28 17:03:17.1182023-03-28 17:03:17.1202023-03-28 17:03:17.1222023-03-28 17:03:17.1232023-03-28 17:03:17.1092023-03-28 17:03:17.1282023-03-28 17:03:17.1292023-03-28 17:03:17.1312023-03-28 17:03:17.1322023-03-28 17:03:17.1342023-03-28 17:03:17.1352023-03-28 17:03:17.1362023-03-28 17:03:17.1372023-03-28 17:03:17.1382023-03-28 17:03:17.1392023-03-28 17:03:17.1402023-03-28 17:03:17.1422023-03-28 17:03:17.1432023-03-28 17:03:17.1442023-03-28 17:03:17.1462023-03-28 17:03:17.1472023-03-28 17:03:17.1482023-03-28 17:03:17.1492023-03-28 17:03:17.1502023-03-28 17:03:17.1512023-03-28 17:03:17.1532023-03-28 17:03:17.1542023-03-28 17:03:17.1552023-03-28 17:03:17.1572023-03-28 17:03:17.1842023-03-28 17:03:17.1922023-03-28 17:03:17.1942023-03-28 17:03:17.1952023-03-28 17:03:17.1972023-03-28 17:03:17.1982023-03-28 17:03:17.1852023-03-28 17:03:17.2012023-03-28 17:03:17.2022023-03-28 17:03:17.2032023-03-28 17:03:17.2042023-03-28 17:03:17.2052023-03-28 17:03:17.2062023-03-28 17:03:17.2082023-03-28 17:03:17.2092023-03-28 17:03:17.2102023-03-28 17:03:17.2112023-03-28 17:03:17.2132023-03-28 17:03:17.2142023-03-28 17:03:17.2152023-03-28 17:03:17.2162023-03-28 17:03:17.2172023-03-28 17:03:17.2182023-03-28 17:03:17.2202023-03-28 17:03:17.2212023-03-28 17:03:17.2222023-03-28 17:03:17.2242023-03-28 17:03:17.2252023-03-28 17:03:17.2262023-03-28 17:03:17.2632023-03-28 17:03:17.2652023-03-28 17:03:17.2682023-03-28 17:03:17.2902023-03-28 17:03:17.2922023-03-28 17:03:17.2932023-03-28 17:03:17.2952023-03-28 17:03:17.2962023-03-28 17:03:17.2722023-03-28 17:03:17.2992023-03-28 17:03:17.3012023-03-28 17:03:17.3032023-03-28 17:03:17.3052023-03-28 17:03:17.3062023-03-28 17:03:17.3072023-03-28 17:03:17.3092023-03-28 17:03:17.3102023-03-28 17:03:17.3592023-03-28 17:03:17.3602023-03-28 17:03:17.3612023-03-28 17:03:17.3632023-03-28 17:03:17.3642023-03-28 17:03:17.3652023-03-28 17:03:17.3662023-03-28 17:03:17.3672023-03-28 17:03:17.3682023-03-28 17:03:17.3702023-03-28 17:03:17.3712023-03-28 17:03:17.3722023-03-28 17:03:17.3742023-03-28 17:03:17.3752023-03-28 17:03:17.3762023-03-28 17:03:17.3772023-03-28 17:03:17.3792023-03-28 17:03:17.3882023-03-28 17:03:17.3902023-03-28 17:03:17.3912023-03-28 17:03:17.3932023-03-28 17:03:17.3942023-03-28 17:03:17.3802023-03-28 17:03:17.3962023-03-28 17:03:17.3982023-03-28 17:03:17.3992023-03-28 17:03:17.4002023-03-28 17:03:17.4022023-03-28 17:03:17.4032023-03-28 17:03:17.4042023-03-28 17:03:17.4062023-03-28 17:03:17.4072023-03-28 17:03:17.4082023-03-28 17:03:17.4102023-03-28 17:03:17.4112023-03-28 17:03:17.4122023-03-28 17:03:17.4132023-03-28 17:03:17.4142023-03-28 17:03:17.4152023-03-28 17:03:17.4162023-03-28 17:03:17.4182023-03-28 17:03:17.4512023-03-28 17:03:17.4532023-03-28 17:03:17.4552023-03-28 17:03:17.4572023-03-28 17:03:17.4592023-03-28 17:03:17.4602023-03-28 17:03:17.4632023-03-28 17:03:17.4722023-03-28 17:03:17.4742023-03-28 17:03:17.4762023-03-28 17:03:17.4772023-03-28 17:03:17.4792023-03-28 17:03:17.4642023-03-28 17:03:17.4812023-03-28 17:03:17.4832023-03-28 17:03:17.4842023-03-28 17:03:17.4852023-03-28 17:03:17.4862023-03-28 17:03:17.4872023-03-28 17:03:17.4882023-03-28 17:03:17.4902023-03-28 17:03:17.4912023-03-28 17:03:17.4932023-03-28 17:03:17.4942023-03-28 17:03:17.4952023-03-28 17:03:17.4962023-03-28 17:03:17.4982023-03-28 17:03:17.4992023-03-28 17:03:17.5002023-03-28 17:03:17.5282023-03-28 17:03:17.5352023-03-28 17:03:17.5372023-03-28 17:03:17.5392023-03-28 17:03:17.5412023-03-28 17:03:17.5422023-03-28 17:03:17.5442023-03-28 17:03:17.5482023-03-28 17:03:17.5512023-03-28 17:03:17.5662023-03-28 17:03:17.5682023-03-28 17:03:17.5692023-03-28 17:03:17.5712023-03-28 17:03:17.5732023-03-28 17:03:17.5542023-03-28 17:03:17.5752023-03-28 17:03:17.5772023-03-28 17:03:17.6062023-03-28 17:03:17.6082023-03-28 17:03:17.6092023-03-28 17:03:17.6102023-03-28 17:03:17.6122023-03-28 17:03:17.6142023-03-28 17:03:17.6162023-03-28 17:03:17.6182023-03-28 17:03:17.6192023-03-28 17:03:17.6212023-03-28 17:03:17.6232023-03-28 17:03:17.6252023-03-28 17:03:17.6282023-03-28 17:03:17.6302023-03-28 17:03:17.6312023-03-28 17:03:17.6332023-03-28 17:03:17.6342023-03-28 17:03:17.6352023-03-28 17:03:17.6362023-03-28 17:03:17.6382023-03-28 17:03:17.6402023-03-28 17:03:17.6422023-03-28 17:03:17.6432023-03-28 17:03:17.6532023-03-28 17:03:17.6542023-03-28 17:03:17.6552023-03-28 17:03:17.6562023-03-28 17:03:17.6582023-03-28 17:03:17.6452023-03-28 17:03:17.6902023-03-28 17:03:17.6912023-03-28 17:03:17.6932023-03-28 17:03:17.6952023-03-28 17:03:17.6972023-03-28 17:03:17.6982023-03-28 17:03:17.7002023-03-28 17:03:17.7012023-03-28 17:03:17.7032023-03-28 17:03:17.7042023-03-28 17:03:17.7062023-03-28 17:03:17.7082023-03-28 17:03:17.7102023-03-28 17:03:17.7112023-03-28 17:03:17.7122023-03-28 17:03:17.7132023-03-28 17:03:17.7152023-03-28 17:03:17.7182023-03-28 17:03:17.7192023-03-28 17:03:17.7202023-03-28 17:03:17.7222023-03-28 17:03:17.7232023-03-28 17:03:17.7242023-03-28 17:03:17.7262023-03-28 17:03:17.7552023-03-28 17:03:17.7642023-03-28 17:03:17.7652023-03-28 17:03:17.7672023-03-28 17:03:17.7682023-03-28 17:03:17.7702023-03-28 17:03:17.7562023-03-28 17:03:17.7722023-03-28 17:03:17.7752023-03-28 17:03:17.7762023-03-28 17:03:17.7782023-03-28 17:03:17.7792023-03-28 17:03:17.7812023-03-28 17:03:17.7822023-03-28 17:03:17.7842023-03-28 17:03:17.7862023-03-28 17:03:17.7882023-03-28 17:03:17.8172023-03-28 17:03:17.8182023-03-28 17:03:17.8202023-03-28 17:03:17.8212023-03-28 17:03:17.8222023-03-28 17:03:17.8232023-03-28 17:03:17.8252023-03-28 17:03:17.8272023-03-28 17:03:17.8282023-03-28 17:03:17.8302023-03-28 17:03:17.8322023-03-28 17:03:17.8342023-03-28 17:03:17.8632023-03-28 17:03:17.8652023-03-28 17:03:17.8672023-03-28 17:03:17.8762023-03-28 17:03:17.8782023-03-28 17:03:17.8802023-03-28 17:03:17.8812023-03-28 17:03:17.8832023-03-28 17:03:17.8692023-03-28 17:03:17.8852023-03-28 17:03:17.8862023-03-28 17:03:17.8872023-03-28 17:03:17.8892023-03-28 17:03:17.8902023-03-28 17:03:17.8912023-03-28 17:03:17.8922023-03-28 17:03:17.8942023-03-28 17:03:17.8952023-03-28 17:03:17.8972023-03-28 17:03:17.8982023-03-28 17:03:17.8992023-03-28 17:03:17.9002023-03-28 17:03:17.9022023-03-28 17:03:17.9032023-03-28 17:03:17.9042023-03-28 17:03:17.9052023-03-28 17:03:17.9072023-03-28 17:03:17.9082023-03-28 17:03:17.9092023-03-28 17:03:17.9372023-03-28 17:03:17.9382023-03-28 17:03:17.9402023-03-28 17:03:17.9412023-03-28 17:03:17.9422023-03-28 17:03:17.9522023-03-28 17:03:17.9532023-03-28 17:03:17.9542023-03-28 17:03:17.9562023-03-28 17:03:17.9572023-03-28 17:03:17.9442023-03-28 17:03:17.9612023-03-28 17:03:17.9622023-03-28 17:03:17.9642023-03-28 17:03:17.9662023-03-28 17:03:17.9672023-03-28 17:03:17.9692023-03-28 17:03:17.9952023-03-28 17:03:17.9962023-03-28 17:03:17.9982023-03-28 17:03:17.9992023-03-28 17:03:18.0002023-03-28 17:03:18.0022023-03-28 17:03:18.0032023-03-28 17:03:18.0042023-03-28 17:03:18.0062023-03-28 17:03:18.0072023-03-28 17:03:18.0092023-03-28 17:03:18.0102023-03-28 17:03:18.0382023-03-28 17:03:18.0392023-03-28 17:03:18.0402023-03-28 17:03:18.0412023-03-28 17:03:18.0432023-03-28 17:03:18.0442023-03-28 17:03:18.0452023-03-28 17:03:18.0542023-03-28 17:03:18.0552023-03-28 17:03:18.0562023-03-28 17:03:18.0572023-03-28 17:03:18.0582023-03-28 17:03:18.0462023-03-28 17:03:18.0612023-03-28 17:03:18.0622023-03-28 17:03:18.0632023-03-28 17:03:18.0642023-03-28 17:03:18.0962023-03-28 17:03:18.0982023-03-28 17:03:18.1002023-03-28 17:03:18.1012023-03-28 17:03:18.1032023-03-28 17:03:18.1042023-03-28 17:03:18.1052023-03-28 17:03:18.1062023-03-28 17:03:18.1072023-03-28 17:03:18.1082023-03-28 17:03:18.1102023-03-28 17:03:18.1112023-03-28 17:03:18.1412023-03-28 17:03:18.1422023-03-28 17:03:18.1432023-03-28 17:03:18.1452023-03-28 17:03:18.1462023-03-28 17:03:18.1482023-03-28 17:03:18.1492023-03-28 17:03:18.1502023-03-28 17:03:18.1512023-03-28 17:03:18.1602023-03-28 17:03:18.1612023-03-28 17:03:18.1632023-03-28 17:03:18.1642023-03-28 17:03:18.1652023-03-28 17:03:18.1522023-03-28 17:03:18.1672023-03-28 17:03:18.1692023-03-28 17:03:18.1702023-03-28 17:03:18.1712023-03-28 17:03:18.1722023-03-28 17:03:18.1732023-03-28 17:03:18.1742023-03-28 17:03:18.1752023-03-28 17:03:18.1762023-03-28 17:03:18.1782023-03-28 17:03:18.1792023-03-28 17:03:18.1802023-03-28 17:03:18.1812023-03-28 17:03:18.1832023-03-28 17:03:18.2112023-03-28 17:03:18.2132023-03-28 17:03:18.2142023-03-28 17:03:18.2152023-03-28 17:03:18.2172023-03-28 17:03:18.2182023-03-28 17:03:18.2192023-03-28 17:03:18.2202023-03-28 17:03:18.2212023-03-28 17:03:18.2232023-03-28 17:03:18.2242023-03-28 17:03:18.2322023-03-28 17:03:18.2342023-03-28 17:03:18.2352023-03-28 17:03:18.2372023-03-28 17:03:18.2382023-03-28 17:03:18.2252023-03-28 17:03:18.2752023-03-28 17:03:18.2762023-03-28 17:03:18.2772023-03-28 17:03:18.2792023-03-28 17:03:18.2812023-03-28 17:03:18.2832023-03-28 17:03:18.2842023-03-28 17:03:18.2852023-03-28 17:03:18.2862023-03-28 17:03:18.2882023-03-28 17:03:18.2892023-03-28 17:03:18.2912023-03-28 17:03:18.3302023-03-28 17:03:18.3312023-03-28 17:03:18.3332023-03-28 17:03:18.3342023-03-28 17:03:18.3352023-03-28 17:03:18.3362023-03-28 17:03:18.3382023-03-28 17:03:18.3392023-03-28 17:03:18.3402023-03-28 17:03:18.3412023-03-28 17:03:18.3432023-03-28 17:03:18.3442023-03-28 17:03:18.3732023-03-28 17:03:18.3842023-03-28 17:03:18.3852023-03-28 17:03:18.3862023-03-28 17:03:18.3872023-03-28 17:03:18.3882023-03-28 17:03:18.3742023-03-28 17:03:18.3912023-03-28 17:03:18.3922023-03-28 17:03:18.3932023-03-28 17:03:18.3942023-03-28 17:03:18.3962023-03-28 17:03:18.3972023-03-28 17:03:18.3982023-03-28 17:03:18.3992023-03-28 17:03:18.4002023-03-28 17:03:18.4012023-03-28 17:03:18.4282023-03-28 17:03:18.4292023-03-28 17:03:18.4312023-03-28 17:03:18.4322023-03-28 17:03:18.4332023-03-28 17:03:18.4342023-03-28 17:03:18.4352023-03-28 17:03:18.4362023-03-28 17:03:18.4372023-03-28 17:03:18.4392023-03-28 17:03:18.4402023-03-28 17:03:18.4412023-03-28 17:03:18.4422023-03-28 17:03:18.4442023-03-28 17:03:18.4452023-03-28 17:03:18.4532023-03-28 17:03:18.4552023-03-28 17:03:18.4562023-03-28 17:03:18.4572023-03-28 17:03:18.4582023-03-28 17:03:18.4462023-03-28 17:03:18.4602023-03-28 17:03:18.4612023-03-28 17:03:18.4622023-03-28 17:03:18.4642023-03-28 17:03:18.4652023-03-28 17:03:18.4662023-03-28 17:03:18.4672023-03-28 17:03:18.4682023-03-28 17:03:18.5032023-03-28 17:03:18.5042023-03-28 17:03:18.5052023-03-28 17:03:18.5062023-03-28 17:03:18.5072023-03-28 17:03:18.5092023-03-28 17:03:18.5102023-03-28 17:03:18.5112023-03-28 17:03:18.5122023-03-28 17:03:18.5142023-03-28 17:03:18.5152023-03-28 17:03:18.5162023-03-28 17:03:18.5452023-03-28 17:03:18.5472023-03-28 17:03:18.5482023-03-28 17:03:18.5492023-03-28 17:03:18.5512023-03-28 17:03:18.5592023-03-28 17:03:18.5612023-03-28 17:03:18.5632023-03-28 17:03:18.5652023-03-28 17:03:18.5662023-03-28 17:03:18.5522023-03-28 17:03:18.5682023-03-28 17:03:18.5702023-03-28 17:03:18.5712023-03-28 17:03:18.5722023-03-28 17:03:18.5732023-03-28 17:03:18.5742023-03-28 17:03:18.6042023-03-28 17:03:18.6062023-03-28 17:03:18.6072023-03-28 17:03:18.6082023-03-28 17:03:18.6102023-03-28 17:03:18.6112023-03-28 17:03:18.6122023-03-28 17:03:18.6142023-03-28 17:03:18.6152023-03-28 17:03:18.6162023-03-28 17:03:18.6172023-03-28 17:03:18.6182023-03-28 17:03:18.6462023-03-28 17:03:18.6482023-03-28 17:03:18.6492023-03-28 17:03:18.6512023-03-28 17:03:18.6522023-03-28 17:03:18.6532023-03-28 17:03:18.6552023-03-28 17:03:18.6642023-03-28 17:03:18.6652023-03-28 17:03:18.6672023-03-28 17:03:18.6682023-03-28 17:03:18.6692023-03-28 17:03:18.6562023-03-28 17:03:18.6722023-03-28 17:03:18.6732023-03-28 17:03:18.6742023-03-28 17:03:18.6752023-03-28 17:03:18.7052023-03-28 17:03:18.7062023-03-28 17:03:18.7072023-03-28 17:03:18.7082023-03-28 17:03:18.7102023-03-28 17:03:18.7112023-03-28 17:03:18.7122023-03-28 17:03:18.7132023-03-28 17:03:18.7142023-03-28 17:03:18.7152023-03-28 17:03:18.7162023-03-28 17:03:18.7172023-03-28 17:03:18.7192023-03-28 17:03:18.7212023-03-28 17:03:18.7222023-03-28 17:03:18.7232023-03-28 17:03:18.7242023-03-28 17:03:18.7262023-03-28 17:03:18.7332023-03-28 17:03:18.7352023-03-28 17:03:18.7372023-03-28 17:03:18.7472023-03-28 17:03:18.7492023-03-28 17:03:18.7512023-03-28 17:03:18.7532023-03-28 17:03:18.7542023-03-28 17:03:18.7392023-03-28 17:03:18.7592023-03-28 17:03:18.7602023-03-28 17:03:18.7882023-03-28 17:03:18.7892023-03-28 17:03:18.7902023-03-28 17:03:18.7922023-03-28 17:03:18.7932023-03-28 17:03:18.7942023-03-28 17:03:18.7952023-03-28 17:03:18.7972023-03-28 17:03:18.7982023-03-28 17:03:18.7992023-03-28 17:03:18.8002023-03-28 17:03:18.8012023-03-28 17:03:18.8282023-03-28 17:03:18.8292023-03-28 17:03:18.8312023-03-28 17:03:18.8322023-03-28 17:03:18.8332023-03-28 17:03:18.8342023-03-28 17:03:18.8352023-03-28 17:03:18.8362023-03-28 17:03:18.8382023-03-28 17:03:18.8392023-03-28 17:03:18.8402023-03-28 17:03:18.8492023-03-28 17:03:18.8512023-03-28 17:03:18.8522023-03-28 17:03:18.8532023-03-28 17:03:18.8542023-03-28 17:03:18.8412023-03-28 17:03:18.8852023-03-28 17:03:18.8862023-03-28 17:03:18.8882023-03-28 17:03:18.8892023-03-28 17:03:18.8902023-03-28 17:03:18.8912023-03-28 17:03:18.8932023-03-28 17:03:18.8942023-03-28 17:03:18.8952023-03-28 17:03:18.8972023-03-28 17:03:18.8992023-03-28 17:03:18.9002023-03-28 17:03:18.9312023-03-28 17:03:18.9332023-03-28 17:03:18.9352023-03-28 17:03:18.9372023-03-28 17:03:18.9382023-03-28 17:03:18.9402023-03-28 17:03:18.9412023-03-28 17:03:18.9422023-03-28 17:03:18.9432023-03-28 17:03:18.9442023-03-28 17:03:18.9452023-03-28 17:03:18.9462023-03-28 17:03:18.9792023-03-28 17:03:18.9882023-03-28 17:03:18.9892023-03-28 17:03:18.9912023-03-28 17:03:18.9922023-03-28 17:03:18.9932023-03-28 17:03:18.9812023-03-28 17:03:18.9962023-03-28 17:03:18.9982023-03-28 17:03:18.9992023-03-28 17:03:19.0002023-03-28 17:03:19.0022023-03-28 17:03:19.0032023-03-28 17:03:19.0042023-03-28 17:03:19.0072023-03-28 17:03:19.0092023-03-28 17:03:19.0112023-03-28 17:03:19.0452023-03-28 17:03:19.0482023-03-28 17:03:19.0502023-03-28 17:03:19.0512023-03-28 17:03:19.0522023-03-28 17:03:19.0542023-03-28 17:03:19.0552023-03-28 17:03:19.0562023-03-28 17:03:19.0572023-03-28 17:03:19.0582023-03-28 17:03:19.0602023-03-28 17:03:19.0612023-03-28 17:03:19.0882023-03-28 17:03:19.0902023-03-28 17:03:19.0922023-03-28 17:03:19.1002023-03-28 17:03:19.1022023-03-28 17:03:19.1032023-03-28 17:03:19.1042023-03-28 17:03:19.1052023-03-28 17:03:19.0932023-03-28 17:03:19.1072023-03-28 17:03:19.1092023-03-28 17:03:19.1102023-03-28 17:03:19.1122023-03-28 17:03:19.1132023-03-28 17:03:19.1142023-03-28 17:03:19.1152023-03-28 17:03:19.1172023-03-28 17:03:19.1442023-03-28 17:03:19.1462023-03-28 17:03:19.1472023-03-28 17:03:19.1492023-03-28 17:03:19.1502023-03-28 17:03:19.1512023-03-28 17:03:19.1522023-03-28 17:03:19.1542023-03-28 17:03:19.1552023-03-28 17:03:19.1562023-03-28 17:03:19.1572023-03-28 17:03:19.1582023-03-28 17:03:19.1602023-03-28 17:03:19.1612023-03-28 17:03:19.1622023-03-28 17:03:19.1642023-03-28 17:03:19.1652023-03-28 17:03:19.1732023-03-28 17:03:19.1752023-03-28 17:03:19.1762023-03-28 17:03:19.1772023-03-28 17:03:19.1782023-03-28 17:03:19.1662023-03-28 17:03:19.1812023-03-28 17:03:19.1822023-03-28 17:03:19.1832023-03-28 17:03:19.1842023-03-28 17:03:19.1862023-03-28 17:03:19.1872023-03-28 17:03:19.2142023-03-28 17:03:19.2162023-03-28 17:03:19.2182023-03-28 17:03:19.2202023-03-28 17:03:19.2212023-03-28 17:03:19.2232023-03-28 17:03:19.2242023-03-28 17:03:19.2262023-03-28 17:03:19.2282023-03-28 17:03:19.2302023-03-28 17:03:19.2312023-03-28 17:03:19.2322023-03-28 17:03:19.2672023-03-28 17:03:19.2682023-03-28 17:03:19.2702023-03-28 17:03:19.2712023-03-28 17:03:19.2722023-03-28 17:03:19.2732023-03-28 17:03:19.2742023-03-28 17:03:19.2832023-03-28 17:03:19.2842023-03-28 17:03:19.2862023-03-28 17:03:19.2872023-03-28 17:03:19.2882023-03-28 17:03:19.2752023-03-28 17:03:19.2902023-03-28 17:03:19.2922023-03-28 17:03:19.2932023-03-28 17:03:19.2942023-03-28 17:03:19.3232023-03-28 17:03:19.3242023-03-28 17:03:19.3252023-03-28 17:03:19.3262023-03-28 17:03:19.3282023-03-28 17:03:19.3292023-03-28 17:03:19.3312023-03-28 17:03:19.3322023-03-28 17:03:19.3332023-03-28 17:03:19.3342023-03-28 17:03:19.3362023-03-28 17:03:19.3372023-03-28 17:03:19.3642023-03-28 17:03:19.3652023-03-28 17:03:19.3672023-03-28 17:03:19.3682023-03-28 17:03:19.3692023-03-28 17:03:19.3712023-03-28 17:03:19.3722023-03-28 17:03:19.3732023-03-28 17:03:19.3742023-03-28 17:03:19.3822023-03-28 17:03:19.3842023-03-28 17:03:19.3852023-03-28 17:03:19.3862023-03-28 17:03:19.3872023-03-28 17:03:19.3752023-03-28 17:03:19.3902023-03-28 17:03:19.3922023-03-28 17:03:19.3932023-03-28 17:03:19.3942023-03-28 17:03:19.3952023-03-28 17:03:19.3972023-03-28 17:03:19.3982023-03-28 17:03:19.3992023-03-28 17:03:19.4002023-03-28 17:03:19.4012023-03-28 17:03:19.4022023-03-28 17:03:19.4032023-03-28 17:03:19.4052023-03-28 17:03:19.4062023-03-28 17:03:19.4382023-03-28 17:03:19.4402023-03-28 17:03:19.4422023-03-28 17:03:19.4442023-03-28 17:03:19.4462023-03-28 17:03:19.4482023-03-28 17:03:19.4492023-03-28 17:03:19.45

In [23]:
eeg_path = "../data/EEG"
gsr_path = "../data/GSR"
psy_path = "../data/PSY"
num_files = 38

folders = {
    "EEG": eeg_path,
    "GSR": gsr_path,
    "PSY": psy_path
}

for f_type, path in folders.items():
    print(f"\n=== {f_type} Data Types ===")
    for i in range(1, num_files + 1):
        file = os.path.join(path, f"{i}_{f_type}.csv")
        if not os.path.exists(file):
            print(f"[WARN] File not found: {file}")
            continue
        df = pd.read_csv(file)
        print(f"\nFile: {i}_{f_type}.csv")
        print(df.dtypes)

=== EEG Data Types ===

File: 1_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 2_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 3_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 4_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 5_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 6_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 7_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 8_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 9_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 10_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 11_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 12_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 13_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 14_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 15_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 16_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 17_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 18_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 19_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 20_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 21_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 22_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 23_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 24_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 25_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 26_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 27_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 28_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 29_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 30_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 31_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 32_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 33_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 34_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 35_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 36_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 37_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 38_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

=== GSR Data Types ===

File: 1_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 2_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 3_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 4_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 5_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 6_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 7_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 8_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 9_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 10_GSR.csv
GSR Resistance CAL     float64

In [30]:
eeg_folder = "../data/EEG"
gsr_folder = "../data/GSR"
output_folder = "../data/merged_data"
os.makedirs(output_folder, exist_ok=True)

num_students = 38

for i in range(1, num_students + 1):
    print(f"Merging EEG + GSR for student {i}...")

    eeg_file = os.path.join(eeg_folder, f"{i}_EEG.csv")
    gsr_file = os.path.join(gsr_folder, f"{i}_GSR.csv")
    
    if not (os.path.exists(eeg_file) and os.path.exists(gsr_file)):
        print(f"[WARN] Missing EEG or GSR file for student {i}, skipping.")
        continue
    
    # Load files
    eeg_df = pd.read_csv(eeg_file)
    gsr_df = pd.read_csv(gsr_file)
    
    # Merge based on UnixTime (nearest match)
    if "UnixTime" in eeg_df.columns and "UnixTime" in gsr_df.columns:
        merged_df = pd.merge_asof(
            eeg_df.sort_values("UnixTime"),
            gsr_df.sort_values("UnixTime"),
            on="UnixTime",
            direction="nearest"
        )
    else:
        merged_df = pd.concat([eeg_df, gsr_df], axis=1)
    
    # Save merged CSV
    output_file = os.path.join(output_folder, f"student_{i}.csv")
    merged_df.to_csv(output_file, index=False)

print("All students merged and saved in 'merged_data' folder.")

Merging EEG + GSR for student 1...
Merging EEG + GSR for student 2...
Merging EEG + GSR for student 3...
Merging EEG + GSR for student 4...
Merging EEG + GSR for student 5...
Merging EEG + GSR for student 6...
Merging EEG + GSR for student 7...
Merging EEG + GSR for student 8...
Merging EEG + GSR for student 9...
Merging EEG + GSR for student 10...
Merging EEG + GSR for student 11...
Merging EEG + GSR for student 12...
Merging EEG + GSR for student 13...
Merging EEG + GSR for student 14...
Merging EEG + GSR for student 15...
Merging EEG + GSR for student 16...
Merging EEG + GSR for student 17...
Merging EEG + GSR for student 18...
Merging EEG + GSR for student 19...
Merging EEG + GSR for student 20...
Merging EEG + GSR for student 21...
Merging EEG + GSR for student 22...
Merging EEG + GSR for student 23...
Merging EEG + GSR for student 24...
Merging EEG + GSR for student 25...
Merging EEG + GSR for student 26...
Merging EEG + GSR for student 27...
Merging EEG + GSR for student 28...
Merging EEG + GSR for student 29...
Merging EEG + GSR for student 30...
Merging EEG + GSR for student 31...
Merging EEG + GSR for student 32...
Merging EEG + GSR for student 33...
Merging EEG + GSR for student 34...
Merging EEG + GSR for student 35...
Merging EEG + GSR for student 36...
Merging EEG + GSR for student 37...
Merging EEG + GSR for student 38...
All students merged and saved in 'merged_data' folder.

In [32]:
merged_folder = "../data/merged_data"  # merged EEG+GSR files
psy_folder = "../data/PSY"             # PSY metadata (1_PSY.csv ... 38_PSY.csv)
output_file = "../data/per_trial_dataset.csv"

num_students = 38
all_trials = []

for i in range(1, num_students + 1):
    print(f"Processing participant {i}...")

    # Load merged EEG+GSR
    merged_file = os.path.join(merged_folder, f"student_{i}.csv")
    psy_file = os.path.join(psy_folder, f"{i}_PSY.csv")  # <- corrected path
    
    if not (os.path.exists(merged_file) and os.path.exists(psy_file)):
        print(f"[WARN] Missing files for participant {i}, skipping.")
        continue
    
    merged_df = pd.read_csv(merged_file)
    psy_df = pd.read_csv(psy_file)

    # Ensure Difficulty numeric
    psy_df['Difficulty'] = pd.to_numeric(psy_df['Difficulty'], errors='coerce')
    psy_df.dropna(subset=['Difficulty'], inplace=True)
    
    if len(psy_df) == 0:
        continue

    # Iterate over trials
    for idx, trial in psy_df.iterrows():
        start, end = trial["routineStart"], trial["routineEnd"]
        label = trial["Difficulty"]
        key = trial.get("Key", idx + 1)

        # Slice merged data for trial window
        segment = merged_df[(merged_df["UnixTime"] >= start) & (merged_df["UnixTime"] <= end)]
        if segment.empty:
            continue

        features = {}

        # Numeric columns (EEG + GSR)
        numeric_cols = segment.select_dtypes(include=np.number).columns
        numeric_cols = [c for c in numeric_cols if c not in ["UnixTime", "Timestamp"]]

        # Aggregate features: mean, std, min, max, median
        for col in numeric_cols:
            features[f"{col}_mean"] = segment[col].mean()
            features[f"{col}_std"] = segment[col].std()
            features[f"{col}_min"] = segment[col].min()
            features[f"{col}_max"] = segment[col].max()
            features[f"{col}_median"] = segment[col].median()

        # Add participant, trial, label
        features['participant'] = i
        features['trial'] = key
        features['label'] = label

        all_trials.append(features)

# Create master DataFrame
master_df = pd.DataFrame(all_trials)
master_df.fillna(0, inplace=True)

# Save CSV
master_df.to_csv(output_file, index=False)
print(f"Per-trial dataset created: {output_file}")

Processing participant 1...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 2...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 3...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 4...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 5...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 6...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 7...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 8...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 9...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 10...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 11...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 12...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 13...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 14...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 15...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 16...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 17...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 18...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 19...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 20...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 21...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 22...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 23...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 24...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 25...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 26...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 27...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 28...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 29...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 30...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 31...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 32...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 33...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 34...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 35...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 36...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 37...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Processing participant 38...

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\2571104058.py:19: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv(merged_file)

Per-trial dataset created: ../data/per_trial_dataset.csv

In [45]:
import pandas as pd
import numpy as np
import os
import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('feature_extraction.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

class EEGGSRFeatureExtractor:
    """Extract per-trial features from EEG+GSR and PSY data files with timestamp synchronization."""
    
    def __init__(self, merged_data_dir: str = "../data/merged_data", psy_data_dir: str = "../data/PSY", 
                 output_dir: str = "../data", target_sampling_rate: float = 250.0):
        self.merged_data_dir = Path(merged_data_dir)
        self.psy_data_dir = Path(psy_data_dir)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        self.target_sampling_rate = target_sampling_rate  # Target sampling rate for alignment

        # EEG frequency bands (Hz)
        self.eeg_bands = {
            'Delta': (0.5, 4),
            'Theta': (4, 8),
            'Alpha': (8, 13),
            'Beta': (13, 30),
            'Gamma': (30, 100)
        }

        # Statistical functions to compute
        self.stat_functions = {
            'mean': np.mean,
            'std': np.std,
            'min': np.min,
            'max': np.max,
            'median': np.median
        }

    def identify_eeg_gsr_columns(self, df: pd.DataFrame) -> Tuple[List[str], List[str]]:
        """Identify EEG and GSR columns from the dataframe."""
        eeg_columns = []
        gsr_columns = []
        for col in df.columns:
            col_lower = col.lower()
            if any(eeg_indicator in col_lower for eeg_indicator in ['eeg', 'electrode', 'channel']):
                eeg_columns.append(col)
            elif any(gsr_indicator in col_lower for gsr_indicator in ['gsr', 'eda', 'conductance']):
                gsr_columns.append(col)
            # Additional heuristics - assume numeric columns that aren't time-related are EEG
            elif col not in ['timestamp', 'time', 'Timestamp', 'Time', 'sample', 'index'] and pd.api.types.is_numeric_dtype(df[col]):
                if 'gsr' in col_lower or 'eda' in col_lower or 'conductance' in col_lower:
                    gsr_columns.append(col)
                else:
                    eeg_columns.append(col)
        logger.info(f"Identified {len(eeg_columns)} EEG columns and {len(gsr_columns)} GSR columns")
        return eeg_columns, gsr_columns

    def synchronize_timestamps(self, merged_df: pd.DataFrame) -> pd.DataFrame:
        """Synchronize and standardize timestamps in the merged dataframe."""
        
        # Find timestamp column
        timestamp_col = None
        for col in ['timestamp', 'time', 'Timestamp', 'Time', 'sample_time']:
            if col in merged_df.columns:
                timestamp_col = col
                break
        
        if timestamp_col is None:
            logger.warning("No timestamp column found, creating synthetic timestamps")
            merged_df = merged_df.copy()
            merged_df['timestamp'] = np.arange(len(merged_df)) / self.target_sampling_rate
            timestamp_col = 'timestamp'
            return merged_df
        
        logger.info(f"Synchronizing timestamps using column: {timestamp_col}")
        
        # Convert timestamp column to numeric if needed
        if not pd.api.types.is_numeric_dtype(merged_df[timestamp_col]):
            logger.info(f"Converting {timestamp_col} from {merged_df[timestamp_col].dtype} to numeric")
            
            # Check if timestamps are datetime strings
            sample_timestamp = str(merged_df[timestamp_col].iloc[0])
            if '-' in sample_timestamp and ':' in sample_timestamp:
                logger.info("Converting datetime strings to Unix timestamps")
                try:
                    merged_df[timestamp_col] = pd.to_datetime(merged_df[timestamp_col]).astype('int64') / 1e9
                    logger.info("Successfully converted datetime strings to Unix timestamps")
                except Exception as e:
                    logger.error(f"Error converting datetime strings: {e}")
                    return merged_df
            else:
                merged_df[timestamp_col] = pd.to_numeric(merged_df[timestamp_col], errors='coerce')
        
        # Check for and handle duplicate or out-of-order timestamps
        if merged_df[timestamp_col].duplicated().any():
            logger.warning("Found duplicate timestamps - removing duplicates")
            merged_df = merged_df.drop_duplicates(subset=[timestamp_col], keep='first')
        
        if not merged_df[timestamp_col].is_monotonic_increasing:
            logger.warning("Timestamps are not in chronological order - sorting by timestamp")
            merged_df = merged_df.sort_values(timestamp_col).reset_index(drop=True)
        
        # Remove any NaN timestamps
        if merged_df[timestamp_col].isna().any():
            logger.warning("Removing rows with NaN timestamps")
            merged_df = merged_df.dropna(subset=[timestamp_col])
        
        logger.info(f"Timestamp synchronization complete. Data shape: {merged_df.shape}")
        return merged_df
    
    def estimate_sampling_rate(self, timestamps: pd.Series) -> float:
        """Estimate the sampling rate from timestamp differences."""
        if len(timestamps) < 2:
            return self.target_sampling_rate
        
        # Calculate time differences between consecutive samples
        time_diffs = timestamps.diff().dropna()
        
        # Remove outliers (keep values within 3 standard deviations)
        mean_diff = time_diffs.mean()
        std_diff = time_diffs.std()
        valid_diffs = time_diffs[abs(time_diffs - mean_diff) <= 3 * std_diff]
        
        if len(valid_diffs) == 0:
            return self.target_sampling_rate
        
        # Calculate sampling rate as 1 / mean_time_difference
        mean_time_diff = valid_diffs.mean()
        estimated_rate = 1.0 / mean_time_diff if mean_time_diff > 0 else self.target_sampling_rate
        
        logger.info(f"Estimated sampling rate: {estimated_rate:.2f} Hz")
        return estimated_rate
    
    def resample_modality_data(self, data: pd.DataFrame, timestamps: pd.Series, 
                              target_rate: float, method: str = 'linear') -> pd.DataFrame:
        """Resample data to target sampling rate for modality alignment."""
        
        if len(data) != len(timestamps):
            logger.error("Data and timestamps length mismatch")
            return data
        
        if len(data) < 2:
            logger.warning("Insufficient data for resampling")
            return data
        
        # Estimate current sampling rate
        current_rate = self.estimate_sampling_rate(timestamps)
        
        if abs(current_rate - target_rate) < 1.0:  # If rates are close, don't resample
            logger.info(f"Sampling rates are close ({current_rate:.2f} vs {target_rate:.2f}), skipping resample")
            return data
        
        logger.info(f"Resampling from {current_rate:.2f} Hz to {target_rate:.2f} Hz using {method} interpolation")
        
        try:
            # Create new timestamp array at target sampling rate
            start_time = timestamps.iloc[0]
            end_time = timestamps.iloc[-1]
            duration = end_time - start_time
            n_new_samples = int(duration * target_rate)
            
            new_timestamps = np.linspace(start_time, end_time, n_new_samples)
            
            # Resample each column
            resampled_data = pd.DataFrame(index=range(n_new_samples))
            resampled_data['timestamp'] = new_timestamps
            
            for col in data.columns:
                if col in ['timestamp', 'time', 'Timestamp', 'Time']:
                    continue  # Skip timestamp columns
                    
                if pd.api.types.is_numeric_dtype(data[col]):
                    # Interpolate numeric data
                    resampled_data[col] = np.interp(new_timestamps, timestamps, data[col])
                else:
                    # For non-numeric data, use forward fill
                    logger.warning(f"Forward filling non-numeric column: {col}")
                    resampled_data[col] = data[col].iloc[0]  # Use first value
            
            logger.info(f"Resampling complete: {len(data)} -> {len(resampled_data)} samples")
            return resampled_data
            
        except Exception as e:
            logger.error(f"Error during resampling: {e}")
            return data
    
    def align_modalities(self, trial_data: pd.DataFrame, eeg_columns: List[str], 
                        gsr_columns: List[str]) -> pd.DataFrame:
        """Align EEG and GSR modalities by resampling to common sampling rate."""
        
        timestamp_col = None
        for col in ['timestamp', 'time', 'Timestamp', 'Time']:
            if col in trial_data.columns:
                timestamp_col = col
                break
        
        if timestamp_col is None:
            logger.warning("No timestamp column found for modality alignment")
            return trial_data
        
        logger.info("Aligning EEG and GSR modalities")
        
        # Separate EEG and GSR data
        eeg_data = trial_data[[timestamp_col] + eeg_columns].copy()
        gsr_data = trial_data[[timestamp_col] + gsr_columns].copy()
        other_data = trial_data.drop(columns=eeg_columns + gsr_columns)
        
        # Estimate sampling rates for each modality
        eeg_rate = self.estimate_sampling_rate(eeg_data[timestamp_col]) if len(eeg_columns) > 0 else self.target_sampling_rate
        gsr_rate = self.estimate_sampling_rate(gsr_data[timestamp_col]) if len(gsr_columns) > 0 else self.target_sampling_rate
        
        logger.info(f"EEG sampling rate: {eeg_rate:.2f} Hz, GSR sampling rate: {gsr_rate:.2f} Hz")
        
        # Choose target sampling rate (use the higher of the two, or target rate)
        target_rate = max(eeg_rate, gsr_rate, self.target_sampling_rate)
        target_rate = min(target_rate, 1000.0)  # Cap at 1000 Hz for practical reasons
        
        logger.info(f"Target alignment sampling rate: {target_rate:.2f} Hz")
        
        # Resample EEG data if needed
        if len(eeg_columns) > 0 and abs(eeg_rate - target_rate) > 1.0:
            eeg_data = self.resample_modality_data(eeg_data, eeg_data[timestamp_col], target_rate)
        
        # Resample GSR data if needed
        if len(gsr_columns) > 0 and abs(gsr_rate - target_rate) > 1.0:
            gsr_data = self.resample_modality_data(gsr_data, gsr_data[timestamp_col], target_rate)
        
        # Merge the aligned data back together
        try:
            if len(eeg_columns) > 0 and len(gsr_columns) > 0:
                # Merge EEG and GSR data on timestamp
                aligned_data = pd.merge_asof(
                    eeg_data.sort_values(timestamp_col), 
                    gsr_data.sort_values(timestamp_col), 
                    on=timestamp_col, 
                    direction='nearest',
                    tolerance=1.0/target_rate  # Allow small timestamp differences
                )
            elif len(eeg_columns) > 0:
                aligned_data = eeg_data
            elif len(gsr_columns) > 0:
                aligned_data = gsr_data
            else:
                aligned_data = trial_data
            
            logger.info(f"Modality alignment complete: {len(trial_data)} -> {len(aligned_data)} samples")
            return aligned_data
            
        except Exception as e:
            logger.error(f"Error during modality alignment: {e}")
            return trial_data
        """Identify EEG and GSR columns from the dataframe."""
        eeg_columns = []
        gsr_columns = []
        
        for col in df.columns:
            col_lower = col.lower()
            if any(eeg_indicator in col_lower for eeg_indicator in ['eeg', 'electrode', 'channel']):
                eeg_columns.append(col)
            elif any(gsr_indicator in col_lower for gsr_indicator in ['gsr', 'eda', 'conductance']):
                gsr_columns.append(col)
            # Additional heuristics - assume numeric columns that aren't time-related are EEG
            elif col not in ['timestamp', 'time', 'Timestamp', 'Time', 'sample', 'index'] and pd.api.types.is_numeric_dtype(df[col]):
                # If we don't have explicit EEG/GSR indicators, assume most numeric columns are EEG
                if 'gsr' in col_lower or 'eda' in col_lower or 'conductance' in col_lower:
                    gsr_columns.append(col)
                else:
                    eeg_columns.append(col)
        
        logger.info(f"Identified {len(eeg_columns)} EEG columns and {len(gsr_columns)} GSR columns")
        return eeg_columns, gsr_columns
    
    def compute_basic_features(self, data: pd.Series, prefix: str) -> Dict[str, float]:
        """Compute basic statistical features for a data series."""
        features = {}
        
        if len(data) == 0 or data.isna().all():
            # Handle empty or all-NaN data
            for stat_name in self.stat_functions.keys():
                features[f"{prefix}_{stat_name}"] = np.nan
            return features
        
        # Remove NaN values for computation
        clean_data = data.dropna()
        
        if len(clean_data) == 0:
            for stat_name in self.stat_functions.keys():
                features[f"{prefix}_{stat_name}"] = np.nan
            return features
        
        for stat_name, stat_func in self.stat_functions.items():
            try:
                features[f"{prefix}_{stat_name}"] = stat_func(clean_data)
            except Exception as e:
                logger.warning(f"Error computing {stat_name} for {prefix}: {e}")
                features[f"{prefix}_{stat_name}"] = np.nan
        
        return features
    
    def find_time_alignment(self, merged_df: pd.DataFrame, psy_df: pd.DataFrame, 
                           timestamp_col: str) -> float:
        """Find the time offset between PSY and merged data timestamps."""
        
        # First, ensure merged data timestamps are converted to numeric
        merged_df_copy = merged_df.copy()
        
        # Convert timestamp column if needed
        if not pd.api.types.is_numeric_dtype(merged_df_copy[timestamp_col]):
            logger.info("Converting merged data timestamps for alignment calculation")
            sample_timestamp = str(merged_df_copy[timestamp_col].iloc[0])
            if '-' in sample_timestamp and ':' in sample_timestamp:
                try:
                    merged_df_copy[timestamp_col] = pd.to_datetime(merged_df_copy[timestamp_col]).astype('int64') / 1e9
                except Exception as e:
                    logger.error(f"Error converting timestamps for alignment: {e}")
                    return 0.0
            else:
                merged_df_copy[timestamp_col] = pd.to_numeric(merged_df_copy[timestamp_col], errors='coerce')
        
        # Get PSY timestamp range
        psy_start_cols = ['routineStart', 'routine_start', 'start_time', 'StartTime']
        psy_end_cols = ['routineEnd', 'routine_end', 'end_time', 'EndTime']
        
        psy_starts = []
        psy_ends = []
        
        for _, trial in psy_df.iterrows():
            for col in psy_start_cols:
                if col in trial.index and pd.notna(trial[col]):
                    try:
                        psy_starts.append(float(trial[col]))
                        break
                    except:
                        continue
                        
            for col in psy_end_cols:
                if col in trial.index and pd.notna(trial[col]):
                    try:
                        psy_ends.append(float(trial[col]))
                        break
                    except:
                        continue
        
        if not psy_starts or not psy_ends:
            logger.error("No valid PSY timestamps found")
            return 0.0
            
        psy_min = min(psy_starts)
        psy_max = max(psy_ends)
        
        # Get merged data timestamp range (now guaranteed to be numeric)
        data_min = merged_df_copy[timestamp_col].min()
        data_max = merged_df_copy[timestamp_col].max()
        
        logger.info(f"PSY timestamp range: {float(psy_min):.2f} - {float(psy_max):.2f}")
        logger.info(f"Merged data timestamp range: {float(data_min):.2f} - {float(data_max):.2f}")
        
        # Calculate potential offsets
        offset_start = float(data_min) - float(psy_min)
        offset_end = float(data_max) - float(psy_max)
        
        logger.info(f"Potential time offsets: start={offset_start:.2f}s, end={offset_end:.2f}s")
        
        # Use the average offset
        offset = (offset_start + offset_end) / 2
        
        # Check if offset makes sense (should be reasonable)
        if abs(offset) > 86400:  # More than 24 hours difference
            logger.warning(f"Large time offset detected: {float(offset):.2f}s ({float(offset)/3600:.2f} hours)")
        
        logger.info(f"Using time offset: {float(offset):.2f}s ({float(offset)/3600:.2f} hours)")
        return float(offset)
        """Compute EEG band-specific features using simple frequency domain analysis."""
        features = {}
        
        if eeg_data.empty:
            for band_name in self.eeg_bands.keys():
                for stat_name in self.stat_functions.keys():
                    features[f"EEG_{band_name}_{stat_name}"] = np.nan
            return features
        
        try:
            from scipy import signal
            from scipy.fft import fft, fftfreq
            
            for col in eeg_data.columns:
                data = eeg_data[col].dropna()
                
                if len(data) < 10:  # Need minimum samples for FFT
                    continue
                
                # Compute FFT
                n = len(data)
                fft_vals = fft(data)
                freqs = fftfreq(n, 1/sampling_rate)
                
                # Compute power spectral density
                psd = np.abs(fft_vals) ** 2
                
                # Extract features for each frequency band
                for band_name, (low_freq, high_freq) in self.eeg_bands.items():
                    # Find frequency indices for this band
                    band_mask = (freqs >= low_freq) & (freqs <= high_freq)
                    
                    if np.sum(band_mask) == 0:
                        continue
                    
                    band_power = psd[band_mask]
                    
                    # Compute statistics for this band
                    for stat_name, stat_func in self.stat_functions.items():
                        feature_name = f"EEG_{col}_{band_name}_{stat_name}"
                        try:
                            features[feature_name] = stat_func(band_power)
                        except:
                            features[feature_name] = np.nan
        
        except ImportError:
            logger.warning("scipy not available - skipping EEG band analysis")
        except Exception as e:
            logger.warning(f"Error in EEG band analysis: {e}")
        
        return features
    
    def load_files(self, participant_id: int) -> Tuple[Optional[pd.DataFrame], Optional[pd.DataFrame]]:
        """Load merged EEG+GSR and PSY files for a participant."""
        # Load merged EEG+GSR file
        merged_file = self.merged_data_dir / f"student_{participant_id}.csv"
        merged_df = None
        
        if merged_file.exists():
            try:
                merged_df = pd.read_csv(merged_file, low_memory=False)
                logger.info(f"Loaded merged data for participant {participant_id}: {merged_df.shape}")
            except Exception as e:
                logger.error(f"Error loading {merged_file}: {e}")
        else:
            logger.warning(f"Merged file not found: {merged_file}")
        
        # Load PSY file
        psy_file = self.psy_data_dir / f"{participant_id}_PSY.csv"
        psy_df = None
        
        if psy_file.exists():
            try:
                psy_df = pd.read_csv(psy_file)
                logger.info(f"Loaded PSY data for participant {participant_id}: {psy_df.shape}")
                
                # Debug: Show the first few rows and column names
                logger.debug(f"PSY columns: {list(psy_df.columns)}")
                logger.debug(f"First PSY row: {psy_df.iloc[0].to_dict() if len(psy_df) > 0 else 'Empty'}")
                
            except Exception as e:
                logger.error(f"Error loading {psy_file}: {e}")
        else:
            logger.warning(f"PSY file not found: {psy_file}")
        
        return merged_df, psy_df
    
    def slice_trial_data(self, merged_df: pd.DataFrame, routine_start: float, 
                        routine_end: float, time_offset: float = 0.0, timestamp_col: str = 'timestamp') -> pd.DataFrame:
        """Slice the merged data for a specific trial based on routine start/end times with proper synchronization."""
        
        logger.info(f"Slicing trial data for time range: {routine_start:.2f} - {routine_end:.2f}")
        
        # Synchronize timestamps first
        synchronized_df = self.synchronize_timestamps(merged_df)
        
        # Find the actual timestamp column after synchronization
        actual_timestamp_col = timestamp_col
        if timestamp_col not in synchronized_df.columns:
            for col in ['timestamp', 'time', 'Timestamp', 'Time', 'sample_time']:
                if col in synchronized_df.columns:
                    actual_timestamp_col = col
                    break
        
        try:
            # Apply time offset to align PSY and merged data timestamps
            adjusted_start = routine_start + time_offset
            adjusted_end = routine_end + time_offset
            
            # Get timestamp range information
            data_min = synchronized_df[actual_timestamp_col].min()
            data_max = synchronized_df[actual_timestamp_col].max()
            
            logger.info(f"Data timestamp range: {float(data_min):.2f} - {float(data_max):.2f}")
            logger.info(f"Adjusted search range: {float(adjusted_start):.2f} - {float(adjusted_end):.2f} (offset: {float(time_offset):.2f}s)")
            
            # Create the mask for slicing
            mask = (synchronized_df[actual_timestamp_col] >= adjusted_start) & \
                   (synchronized_df[actual_timestamp_col] <= adjusted_end)
            trial_data = synchronized_df[mask].copy()
            
            if trial_data.empty:
                logger.warning(f"No data found for adjusted time range {float(adjusted_start):.2f} - {float(adjusted_end):.2f}")
                
                # Try to find the closest available data
                closest_start_idx = (synchronized_df[actual_timestamp_col] - adjusted_start).abs().idxmin()
                closest_end_idx = (synchronized_df[actual_timestamp_col] - adjusted_end).abs().idxmin()
                
                logger.info(f"Closest start time: {float(synchronized_df.loc[closest_start_idx, actual_timestamp_col]):.2f}")
                logger.info(f"Closest end time: {float(synchronized_df.loc[closest_end_idx, actual_timestamp_col]):.2f}")
                
                return pd.DataFrame()
            else:
                logger.info(f"Successfully sliced {len(trial_data)} samples for trial")
                
                # Validate that we have reasonable trial duration
                actual_duration = float(trial_data[actual_timestamp_col].max() - trial_data[actual_timestamp_col].min())
                expected_duration = float(routine_end - routine_start)
                
                if abs(actual_duration - expected_duration) > expected_duration * 0.1:  # More than 10% difference
                    logger.warning(f"Trial duration mismatch: expected {expected_duration:.2f}s, got {actual_duration:.2f}s")
                
            return trial_data
            
        except Exception as e:
            logger.error(f"Error slicing trial data: {e}")
            return pd.DataFrame()
    
    def process_trial(self, merged_df: pd.DataFrame, trial_info: pd.Series, 
                     eeg_columns: List[str], gsr_columns: List[str], time_offset: float = 0.0) -> Dict[str, any]:
        """Process a single trial and compute features."""
        
        # Extract trial information with multiple possible column names
        routine_start = None
        routine_end = None
        trial_key = None
        difficulty = None
        
        # Try different possible column names for routine start/end
        for start_col in ['routineStart', 'routine_start', 'start_time', 'StartTime']:
            if start_col in trial_info.index and pd.notna(trial_info[start_col]):
                routine_start = trial_info[start_col]
                break
        
        for end_col in ['routineEnd', 'routine_end', 'end_time', 'EndTime']:
            if end_col in trial_info.index and pd.notna(trial_info[end_col]):
                routine_end = trial_info[end_col]
                break
        
        # Try different possible column names for trial identifier
        for key_col in ['Key', 'key', 'trial', 'Trial', 'trial_id']:
            if key_col in trial_info.index and pd.notna(trial_info[key_col]):
                trial_key = trial_info[key_col]
                break
        
        # Try different possible column names for difficulty/label
        for diff_col in ['Difficulty', 'difficulty', 'label', 'Label', 'condition']:
            if diff_col in trial_info.index and pd.notna(trial_info[diff_col]):
                difficulty = trial_info[diff_col]
                break
        
        # Debug: Show what we found
        logger.debug(f"Trial info columns: {trial_info.index.tolist()}")
        logger.debug(f"Found - start: {routine_start}, end: {routine_end}, key: {trial_key}, difficulty: {difficulty}")
        
        # Convert to numeric if they're strings
        try:
            routine_start = float(routine_start) if routine_start is not None else None
            routine_end = float(routine_end) if routine_end is not None else None
        except (ValueError, TypeError):
            logger.warning(f"Cannot convert routine times to numeric: start={routine_start}, end={routine_end}")
            routine_start = None
            routine_end = None
        
        if routine_start is None or routine_end is None:
            logger.warning(f"Missing or invalid routine start/end times for trial {trial_key}")
            return None
        
        # Slice trial data with proper synchronization
        trial_data = self.slice_trial_data(merged_df, routine_start, routine_end, time_offset)
        
        if trial_data.empty:
            logger.warning(f"No data available for trial {trial_key}")
            return None
        
        # Align EEG and GSR modalities if both are present
        if len(eeg_columns) > 0 or len(gsr_columns) > 0:
            logger.info(f"Aligning modalities for trial {trial_key}")
            trial_data = self.align_modalities(trial_data, eeg_columns, gsr_columns)
        
        # Initialize feature dictionary with synchronization info
        #sampling_rate = self.estimate_sampling_rate(trial_data[trial_data.columns[trial_data.columns.str.contains('timestamp|time', case=False, na=False)].iloc[0]] if any(trial_data.columns.str.contains('timestamp|time', case=False, na=False)) else trial_data.index.to_series())
        # Find timestamp column for sampling rate estimation
        timestamp_col = None
        for col in ['timestamp', 'time', 'Timestamp', 'Time', 'sample_time']:
            if col in trial_data.columns:
                timestamp_col = col
                break

        if timestamp_col:
            sampling_rate = self.estimate_sampling_rate(trial_data[timestamp_col])
        else:
            sampling_rate = self.target_sampling_rate

        features = {
            'trial': trial_key,
            'label': difficulty,
            'routine_start': routine_start,
            'routine_end': routine_end,
            'trial_duration': routine_end - routine_start,
            'n_samples': len(trial_data),
            'sampling_rate': sampling_rate,
            'data_quality_score': self.calculate_data_quality_score(trial_data, eeg_columns, gsr_columns)
        }
        
        # Compute EEG features
        for eeg_col in eeg_columns:
            if eeg_col in trial_data.columns:
                eeg_features = self.compute_basic_features(trial_data[eeg_col], f"EEG_{eeg_col}")
                features.update(eeg_features)
        
        # Compute GSR features
        for gsr_col in gsr_columns:
            if gsr_col in trial_data.columns:
                gsr_features = self.compute_basic_features(trial_data[gsr_col], f"GSR_{gsr_col}")
                features.update(gsr_features)
        
        # Compute overall EEG and GSR statistics
        if eeg_columns:
            available_eeg_cols = [col for col in eeg_columns if col in trial_data.columns]
            if available_eeg_cols:
                eeg_data = trial_data[available_eeg_cols]
                overall_eeg_features = self.compute_basic_features(
                    eeg_data.values.flatten(), "EEG_overall"
                )
                features.update(overall_eeg_features)
                
                # Compute EEG band features if requested
                band_features = self.compute_eeg_band_features(eeg_data)
                features.update(band_features)
        
        if gsr_columns:
            available_gsr_cols = [col for col in gsr_columns if col in trial_data.columns]
            if available_gsr_cols:
                gsr_data = trial_data[available_gsr_cols]
                overall_gsr_features = self.compute_basic_features(
                    gsr_data.values.flatten(), "GSR_overall"
                )
                features.update(overall_gsr_features)
        
        logger.info(f"Successfully processed trial {trial_key} with {len(trial_data)} samples (SR: {sampling_rate:.2f} Hz)")
        return features
    
    def calculate_data_quality_score(self, trial_data: pd.DataFrame, eeg_columns: List[str], 
                                   gsr_columns: List[str]) -> float:
        """Calculate a data quality score for the trial (0-1 scale, 1 = best quality)."""
        
        if trial_data.empty:
            return 0.0
        
        quality_factors = []
        
        # Factor 1: Data completeness (no NaN values)
        total_values = trial_data[eeg_columns + gsr_columns].size
        non_nan_values = trial_data[eeg_columns + gsr_columns].count().sum()
        completeness = non_nan_values / total_values if total_values > 0 else 0.0
        quality_factors.append(completeness)
        
        # Factor 2: Signal stability (low variance in differences indicates stable signal)
        stability_scores = []
        for col in eeg_columns + gsr_columns:
            if col in trial_data.columns and len(trial_data[col].dropna()) > 1:
                signal = trial_data[col].dropna()
                signal_diff = signal.diff().dropna()
                if len(signal_diff) > 0:
                    # Normalize by signal range to get relative stability
                    signal_range = signal.max() - signal.min()
                    if signal_range > 0:
                        stability = 1.0 / (1.0 + signal_diff.std() / signal_range)
                        stability_scores.append(stability)
        
        if stability_scores:
            quality_factors.append(np.mean(stability_scores))
        
        # Factor 3: Temporal consistency (regular sampling)
        timestamp_col = None
        for col in ['timestamp', 'time', 'Timestamp', 'Time']:
            if col in trial_data.columns:
                timestamp_col = col
                break
        
        if timestamp_col and len(trial_data) > 2:
            time_diffs = trial_data[timestamp_col].diff().dropna()
            if len(time_diffs) > 0:
                # Higher score for more consistent time differences
                consistency = 1.0 / (1.0 + time_diffs.std() / time_diffs.mean() if time_diffs.mean() > 0 else 1.0)
                quality_factors.append(consistency)
        
        # Combine all quality factors
        overall_quality = np.mean(quality_factors) if quality_factors else 0.5
        return min(1.0, max(0.0, overall_quality))
    
    def process_participant(self, participant_id: int) -> List[Dict[str, any]]:
        """Process all trials for a single participant."""
        logger.info(f"Processing participant {participant_id}")
        
        # Load files
        merged_df, psy_df = self.load_files(participant_id)
        
        if merged_df is None or psy_df is None:
            logger.warning(f"Skipping participant {participant_id} - missing files")
            return []
        
        # Debug: Show merged data columns and timestamp info
        logger.debug(f"Merged data columns: {list(merged_df.columns)}")
        
        # Calculate time alignment offset
        timestamp_col = None
        for col in ['timestamp', 'time', 'Timestamp', 'Time', 'sample_time']:
            if col in merged_df.columns:
                timestamp_col = col
                break
        
        time_offset = 0.0
        if timestamp_col:
            time_offset = self.find_time_alignment(merged_df, psy_df, timestamp_col)
        
        # Identify EEG and GSR columns
        eeg_columns, gsr_columns = self.identify_eeg_gsr_columns(merged_df)
        
        if not eeg_columns and not gsr_columns:
            logger.warning(f"No EEG or GSR columns found for participant {participant_id}")
            return []
        
        # Process each trial
        trial_features = []
        
        for idx, trial_info in psy_df.iterrows():
            logger.debug(f"Processing trial {idx}")
            features = self.process_trial(merged_df, trial_info, eeg_columns, gsr_columns, time_offset)
            
            if features is not None:
                features['participant'] = participant_id
                trial_features.append(features)
            else:
                logger.warning(f"Failed to process trial {idx} for participant {participant_id}")
        
        logger.info(f"Successfully processed {len(trial_features)} trials for participant {participant_id}")
        return trial_features
    
    def run_feature_extraction(self, participant_range: range = range(1, 39)) -> pd.DataFrame:
        """Run feature extraction for all participants."""
        logger.info("Starting feature extraction process")
        
        all_trial_features = []
        
        for participant_id in participant_range:
            try:
                participant_features = self.process_participant(participant_id)
                all_trial_features.extend(participant_features)
            except Exception as e:
                logger.error(f"Error processing participant {participant_id}: {e}")
                continue
        
        if not all_trial_features:
            logger.error("No features extracted for any participant")
            return pd.DataFrame()
        
        # Convert to DataFrame
        feature_df = pd.DataFrame(all_trial_features)
        
        # Reorder columns for better readability
        priority_columns = ['participant', 'trial', 'label', 'routine_start', 'routine_end', 
                          'trial_duration', 'n_samples']
        other_columns = [col for col in feature_df.columns if col not in priority_columns]
        ordered_columns = priority_columns + sorted(other_columns)
        
        feature_df = feature_df[[col for col in ordered_columns if col in feature_df.columns]]
        
        logger.info(f"Feature extraction complete. Final dataset shape: {feature_df.shape}")
        logger.info(f"Features extracted: {len(feature_df.columns)} columns")
        
        return feature_df
    
    def save_dataset(self, feature_df: pd.DataFrame, filename: str = "per_trial_dataset.csv"):
        """Save the per-trial dataset."""
        output_path = self.output_dir / filename
        feature_df.to_csv(output_path, index=False)
        logger.info(f"Dataset saved to: {output_path}")
        
        # Print summary statistics
        print("\n" + "="*60)
        print("FEATURE EXTRACTION SUMMARY")
        print("="*60)
        print(f"Total trials processed: {len(feature_df)}")
        print(f"Number of participants: {feature_df['participant'].nunique()}")
        print(f"Number of features: {len(feature_df.columns)}")
        print(f"Labels distribution:")
        if 'label' in feature_df.columns:
            print(feature_df['label'].value_counts())
        print(f"Output saved to: {output_path}")


def main():
    """Main function to run the feature extraction with timestamp synchronization."""
    
    # Initialize the feature extractor with target sampling rate
    extractor = EEGGSRFeatureExtractor(
        merged_data_dir="../data/merged_data",
        psy_data_dir="../data/PSY",
        output_dir="../data",
        target_sampling_rate=250.0  # Set target sampling rate for alignment
    )
    
    # Run feature extraction for participants 1-38
    feature_df = extractor.run_feature_extraction(range(1, 39))
    
    if not feature_df.empty:
        # Save the dataset
        extractor.save_dataset(feature_df)
        
        # Display first few rows
        print("\nFirst 5 rows of the dataset:")
        print(feature_df.head())
        
        print("\nDataset info:")
        print(feature_df.info())
    else:
        logger.error("No data was processed successfully")


if __name__ == "__main__":
    main()

2025-09-21 15:55:38,110 - INFO - Starting feature extraction process
2025-09-21 15:55:38,115 - INFO - Processing participant 1
2025-09-21 15:55:40,436 - INFO - Loaded merged data for participant 1: (203240, 24)
2025-09-21 15:55:40,458 - INFO - Loaded PSY data for participant 1: (40, 3)
2025-09-21 15:55:40,556 - INFO - Converting merged data timestamps for alignment calculation
2025-09-21 15:55:41,305 - INFO - PSY timestamp range: 1680003249.79 - 1680003799.93
2025-09-21 15:55:41,307 - INFO - Merged data timestamp range: 1680022996.77 - 1680023662.34
2025-09-21 15:55:41,309 - INFO - Potential time offsets: start=19746.98s, end=19862.41s
2025-09-21 15:55:41,314 - INFO - Using time offset: 19804.70s (5.50 hours)
2025-09-21 15:55:41,334 - INFO - Identified 20 EEG columns and 2 GSR columns
2025-09-21 15:55:41,339 - INFO - Slicing trial data for time range: 1680003249.79 - 1680003260.16
2025-09-21 15:55:41,344 - INFO - Synchronizing timestamps using column: Timestamp
2025-09-21 15:55:41,351 - INFO - Converting Timestamp from object to numeric
2025-09-21 15:55:41,353 - INFO - Converting datetime strings to Unix timestamps
2025-09-21 15:55:41,864 - INFO - Successfully converted datetime strings to Unix timestamps
2025-09-21 15:55:41,888 - WARNING - Found duplicate timestamps - removing duplicates
2025-09-21 15:55:41,975 - WARNING - Timestamps are not in chronological order - sorting by timestamp
2025-09-21 15:55:42,209 - INFO - Timestamp synchronization complete. Data shape: (203231, 24)
2025-09-21 15:55:42,216 - INFO - Data timestamp range: 1680022996.77 - 1680023662.34
2025-09-21 15:55:42,219 - INFO - Adjusted search range: 1680023054.49 - 1680023064.86 (offset: 19804.70s)
2025-09-21 15:55:42,225 - INFO - Successfully sliced 3162 samples for trial
2025-09-21 15:55:42,248 - INFO - Aligning modalities for trial None
2025-09-21 15:55:42,252 - INFO - Aligning EEG and GSR modalities
2025-09-21 15:55:42,279 - INFO - Estimated sampling rate: 617.79 Hz
2025-09-21 15:55:42,290 - INFO - Estimated sampling rate: 617.79 Hz
2025-09-21 15:55:42,293 - INFO - EEG sampling rate: 617.79 Hz, GSR sampling rate: 617.79 Hz
2025-09-21 15:55:42,300 - INFO - Target alignment sampling rate: 617.79 Hz
2025-09-21 15:55:42,315 - INFO - Modality alignment complete: 3162 -> 3162 samples
2025-09-21 15:55:42,348 - INFO - Estimated sampling rate: 617.79 Hz
2025-09-21 15:55:42,759 - ERROR - Error processing participant 1: 'numpy.ndarray' object has no attribute 'isna'
2025-09-21 15:55:42,773 - INFO - Processing participant 2
2025-09-21 15:55:44,644 - INFO - Loaded merged data for participant 2: (294961, 24)
2025-09-21 15:55:44,741 - INFO - Loaded PSY data for participant 2: (33, 3)
2025-09-21 15:55:44,773 - INFO - Converting merged data timestamps for alignment calculation
2025-09-21 15:55:45,056 - INFO - PSY timestamp range: 1676984654.01 - 1676985390.64
2025-09-21 15:55:45,057 - INFO - Merged data timestamp range: 1677004252.30 - 1677005217.73
2025-09-21 15:55:45,058 - INFO - Potential time offsets: start=19598.30s, end=19827.09s
2025-09-21 15:55:45,062 - INFO - Using time offset: 19712.69s (5.48 hours)
2025-09-21 15:55:45,086 - INFO - Identified 20 EEG columns and 2 GSR columns
2025-09-21 15:55:45,088 - INFO - Slicing trial data for time range: 1676984654.01 - 1676984664.81
2025-09-21 15:55:45,092 - INFO - Synchronizing timestamps using column: Timestamp
2025-09-21 15:55:45,096 - INFO - Converting Timestamp from object to numeric
2025-09-21 15:55:45,098 - INFO - Converting datetime strings to Unix timestamps
2025-09-21 15:55:45,351 - INFO - Successfully converted datetime strings to Unix timestamps
2025-09-21 15:55:45,374 - WARNING - Found duplicate timestamps - removing duplicates
2025-09-21 15:55:45,448 - WARNING - Timestamps are not in chronological order - sorting by timestamp
2025-09-21 15:55:45,609 - INFO - Timestamp synchronization complete. Data shape: (294872, 24)
2025-09-21 15:55:45,616 - INFO - Data timestamp range: 1677004252.30 - 1677005217.73
2025-09-21 15:55:45,618 - INFO - Adjusted search range: 1677004366.70 - 1677004377.50 (offset: 19712.69s)
2025-09-21 15:55:45,628 - INFO - Successfully sliced 3297 samples for trial
2025-09-21 15:55:45,645 - INFO - Aligning modalities for trial None
2025-09-21 15:55:45,648 - INFO - Aligning EEG and GSR modalities
2025-09-21 15:55:45,658 - INFO - Estimated sampling rate: 599.77 Hz
2025-09-21 15:55:45,665 - INFO - Estimated sampling rate: 599.77 Hz
2025-09-21 15:55:45,667 - INFO - EEG sampling rate: 599.77 Hz, GSR sampling rate: 599.77 Hz
2025-09-21 15:55:45,683 - INFO - Target alignment sampling rate: 599.77 Hz
2025-09-21 15:55:45,694 - INFO - Modality alignment complete: 3297 -> 3297 samples
2025-09-21 15:55:45,703 - INFO - Estimated sampling rate: 599.77 Hz
2025-09-21 15:55:45,779 - ERROR - Error processing participant 2: 'numpy.ndarray' object has no attribute 'isna'
2025-09-21 15:55:45,798 - INFO - Processing participant 3
2025-09-21 15:55:49,221 - INFO - Loaded merged data for participant 3: (369917, 24)
2025-09-21 15:55:49,247 - INFO - Loaded PSY data for participant 3: (42, 3)
2025-09-21 15:55:49,301 - INFO - Converting merged data timestamps for alignment calculation
2025-09-21 15:55:49,724 - INFO - PSY timestamp range: 1678717040.11 - 1678718038.85
2025-09-21 15:55:49,729 - INFO - Merged data timestamp range: 1678736631.84 - 1678737842.46
2025-09-21 15:55:49,732 - INFO - Potential time offsets: start=19591.73s, end=19803.61s
2025-09-21 15:55:49,734 - INFO - Using time offset: 19697.67s (5.47 hours)
2025-09-21 15:55:49,769 - INFO - Identified 20 EEG columns and 2 GSR columns
2025-09-21 15:55:49,772 - INFO - Slicing trial data for time range: 1678717040.11 - 1678717059.26
2025-09-21 15:55:49,774 - INFO - Synchronizing timestamps using column: Timestamp
2025-09-21 15:55:49,780 - INFO - Converting Timestamp from object to numeric
2025-09-21 15:55:49,784 - INFO - Converting datetime strings to Unix timestamps
2025-09-21 15:55:50,271 - INFO - Successfully converted datetime strings to Unix timestamps
2025-09-21 15:55:50,315 - WARNING - Found duplicate timestamps - removing duplicates
2025-09-21 15:55:50,400 - WARNING - Timestamps are not in chronological order - sorting by timestamp
2025-09-21 15:55:50,697 - INFO - Timestamp synchronization complete. Data shape: (369774, 24)
2025-09-21 15:55:50,701 - INFO - Data timestamp range: 1678736631.84 - 1678737842.46
2025-09-21 15:55:50,703 - INFO - Adjusted search range: 1678736737.78 - 1678736756.92 (offset: 19697.67s)
2025-09-21 15:55:50,714 - INFO - Successfully sliced 5847 samples for trial
2025-09-21 15:55:50,755 - INFO - Aligning modalities for trial None
2025-09-21 15:55:50,758 - INFO - Aligning EEG and GSR modalities
2025-09-21 15:55:50,791 - INFO - Estimated sampling rate: 611.83 Hz
2025-09-21 15:55:50,800 - INFO - Estimated sampling rate: 611.83 Hz
2025-09-21 15:55:50,803 - INFO - EEG sampling rate: 611.83 Hz, GSR sampling rate: 611.83 Hz
2025-09-21 15:55:50,805 - INFO - Target alignment sampling rate: 611.83 Hz
2025-09-21 15:55:50,841 - INFO - Modality alignment complete: 5847 -> 5847 samples
2025-09-21 15:55:50,851 - INFO - Estimated sampling rate: 611.83 Hz
2025-09-21 15:55:50,972 - ERROR - Error processing participant 3: 'numpy.ndarray' object has no attribute 'isna'
2025-09-21 15:55:51,000 - INFO - Processing participant 4
2025-09-21 15:55:53,327 - INFO - Loaded merged data for participant 4: (286640, 24)
2025-09-21 15:55:53,348 - INFO - Loaded PSY data for participant 4: (42, 3)
2025-09-21 15:55:53,388 - INFO - Converting merged data timestamps for alignment calculation
2025-09-21 15:55:53,761 - INFO - PSY timestamp range: 1676378840.63 - 1676379606.74
2025-09-21 15:55:53,764 - INFO - Merged data timestamp range: 1676398557.37 - 1676399495.81
2025-09-21 15:55:53,765 - INFO - Potential time offsets: start=19716.74s, end=19889.07s
2025-09-21 15:55:53,767 - INFO - Using time offset: 19802.91s (5.50 hours)
2025-09-21 15:55:53,788 - INFO - Identified 20 EEG columns and 2 GSR columns
2025-09-21 15:55:53,791 - INFO - Slicing trial data for time range: 1676378840.63 - 1676378849.90
2025-09-21 15:55:53,794 - INFO - Synchronizing timestamps using column: Timestamp
2025-09-21 15:55:53,796 - INFO - Converting Timestamp from object to numeric
2025-09-21 15:55:53,803 - INFO - Converting datetime strings to Unix timestamps
2025-09-21 15:55:54,108 - INFO - Successfully converted datetime strings to Unix timestamps
2025-09-21 15:55:54,133 - WARNING - Found duplicate timestamps - removing duplicates
2025-09-21 15:55:54,221 - WARNING - Timestamps are not in chronological order - sorting by timestamp
2025-09-21 15:55:54,379 - INFO - Timestamp synchronization complete. Data shape: (286572, 24)
2025-09-21 15:55:54,382 - INFO - Data timestamp range: 1676398557.37 - 1676399495.81
2025-09-21 15:55:54,384 - INFO - Adjusted search range: 1676398643.53 - 1676398652.80 (offset: 19802.91s)
2025-09-21 15:55:54,390 - INFO - Successfully sliced 2827 samples for trial
2025-09-21 15:55:54,405 - INFO - Aligning modalities for trial None
2025-09-21 15:55:54,408 - INFO - Aligning EEG and GSR modalities
2025-09-21 15:55:54,421 - INFO - Estimated sampling rate: 570.58 Hz
2025-09-21 15:55:54,431 - INFO - Estimated sampling rate: 570.58 Hz
2025-09-21 15:55:54,433 - INFO - EEG sampling rate: 570.58 Hz, GSR sampling rate: 570.58 Hz
2025-09-21 15:55:54,435 - INFO - Target alignment sampling rate: 570.58 Hz
2025-09-21 15:55:54,447 - INFO - Modality alignment complete: 2827 -> 2827 samples
2025-09-21 15:55:54,454 - INFO - Estimated sampling rate: 570.58 Hz
2025-09-21 15:55:54,590 - ERROR - Error processing participant 4: 'numpy.ndarray' object has no attribute 'isna'
2025-09-21 15:55:54,615 - INFO - Processing participant 5
2025-09-21 15:55:57,470 - INFO - Loaded merged data for participant 5: (388447, 24)
2025-09-21 15:55:57,501 - INFO - Loaded PSY data for participant 5: (44, 3)
2025-09-21 15:55:57,568 - INFO - Converting merged data timestamps for alignment calculation
2025-09-21 15:55:58,044 - INFO - PSY timestamp range: 1676462372.26 - 1676463355.49
2025-09-21 15:55:58,046 - INFO - Merged data timestamp range: 1676481967.59 - 1676483238.06
2025-09-21 15:55:58,047 - INFO - Potential time offsets: start=19595.33s, end=19882.57s
2025-09-21 15:55:58,049 - INFO - Using time offset: 19738.95s (5.48 hours)
2025-09-21 15:55:58,080 - INFO - Identified 20 EEG columns and 2 GSR columns
2025-09-21 15:55:58,085 - INFO - Slicing trial data for time range: 1676462372.26 - 1676462404.78
2025-09-21 15:55:58,095 - INFO - Synchronizing timestamps using column: Timestamp
2025-09-21 15:55:58,099 - INFO - Converting Timestamp from object to numeric
2025-09-21 15:55:58,103 - INFO - Converting datetime strings to Unix timestamps
2025-09-21 15:55:58,555 - INFO - Successfully converted datetime strings to Unix timestamps
2025-09-21 15:55:58,587 - WARNING - Found duplicate timestamps - removing duplicates
2025-09-21 15:55:58,684 - WARNING - Timestamps are not in chronological order - sorting by timestamp
2025-09-21 15:55:58,952 - INFO - Timestamp synchronization complete. Data shape: (388238, 24)
2025-09-21 15:55:58,955 - INFO - Data timestamp range: 1676481967.59 - 1676483238.06
2025-09-21 15:55:58,958 - INFO - Adjusted search range: 1676482111.21 - 1676482143.73 (offset: 19738.95s)
2025-09-21 15:55:58,995 - INFO - Successfully sliced 9923 samples for trial
2025-09-21 15:55:59,013 - INFO - Aligning modalities for trial None
2025-09-21 15:55:59,015 - INFO - Aligning EEG and GSR modalities
2025-09-21 15:55:59,024 - INFO - Estimated sampling rate: 590.75 Hz
2025-09-21 15:55:59,033 - INFO - Estimated sampling rate: 590.75 Hz
2025-09-21 15:55:59,034 - INFO - EEG sampling rate: 590.75 Hz, GSR sampling rate: 590.75 Hz
2025-09-21 15:55:59,036 - INFO - Target alignment sampling rate: 590.75 Hz
2025-09-21 15:55:59,052 - INFO - Modality alignment complete: 9923 -> 9923 samples
2025-09-21 15:55:59,057 - INFO - Estimated sampling rate: 590.75 Hz
2025-09-21 15:55:59,139 - ERROR - Error processing participant 5: 'numpy.ndarray' object has no attribute 'isna'
2025-09-21 15:55:59,187 - INFO - Processing participant 6
2025-09-21 15:56:01,369 - INFO - Loaded merged data for participant 6: (325134, 24)
2025-09-21 15:56:01,412 - INFO - Loaded PSY data for participant 6: (20, 3)
2025-09-21 15:56:01,441 - INFO - Converting merged data timestamps for alignment calculation
2025-09-21 15:56:01,858 - INFO - PSY timestamp range: 1679142861.40 - 1679143679.60
2025-09-21 15:56:01,860 - INFO - Merged data timestamp range: 1679162408.83 - 1679163473.64
2025-09-21 15:56:01,861 - INFO - Potential time offsets: start=19547.43s, end=19794.04s
2025-09-21 15:56:01,862 - INFO - Using time offset: 19670.73s (5.46 hours)
2025-09-21 15:56:01,889 - INFO - Identified 20 EEG columns and 2 GSR columns
2025-09-21 15:56:01,893 - INFO - Slicing trial data for time range: 1679142861.40 - 1679142894.73
2025-09-21 15:56:01,896 - INFO - Synchronizing timestamps using column: Timestamp
2025-09-21 15:56:01,898 - INFO - Converting Timestamp from object to numeric
2025-09-21 15:56:01,903 - INFO - Converting datetime strings to Unix timestamps
2025-09-21 15:56:02,197 - INFO - Successfully converted datetime strings to Unix timestamps
2025-09-21 15:56:02,228 - WARNING - Found duplicate timestamps - removing duplicates
2025-09-21 15:56:02,312 - WARNING - Timestamps are not in chronological order - sorting by timestamp
2025-09-21 15:56:02,482 - INFO - Timestamp synchronization complete. Data shape: (325119, 24)
2025-09-21 15:56:02,485 - INFO - Data timestamp range: 1679162408.83 - 1679163473.64
2025-09-21 15:56:02,487 - INFO - Adjusted search range: 1679162532.13 - 1679162565.46 (offset: 19670.73s)
2025-09-21 15:56:02,497 - INFO - Successfully sliced 10181 samples for trial
2025-09-21 15:56:02,514 - INFO - Aligning modalities for trial None
2025-09-21 15:56:02,518 - INFO - Aligning EEG and GSR modalities
2025-09-21 15:56:02,531 - INFO - Estimated sampling rate: 596.02 Hz
2025-09-21 15:56:02,536 - INFO - Estimated sampling rate: 596.02 Hz
2025-09-21 15:56:02,538 - INFO - EEG sampling rate: 596.02 Hz, GSR sampling rate: 596.02 Hz
2025-09-21 15:56:02,540 - INFO - Target alignment sampling rate: 596.02 Hz
2025-09-21 15:56:02,558 - INFO - Modality alignment complete: 10181 -> 10181 samples
2025-09-21 15:56:02,566 - INFO - Estimated sampling rate: 596.02 Hz
2025-09-21 15:56:02,662 - ERROR - Error processing participant 6: 'numpy.ndarray' object has no attribute 'isna'
2025-09-21 15:56:02,680 - INFO - Processing participant 7

KeyboardInterrupt: