In [ ]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
from pathlib import Path
import shutil
import pandas as pd
import os
import numpy as np

In [ ]:
def create_feature_dataset(participant_id):
    """
    Processes and extracts features for a single participant.
    """
    # --- 1. Load Data ---
    try:
        eeg_df = pd.read_csv(f'../stdata/1/{participant_id}_EEG.csv')
        gsr_df = pd.read_csv(f'../stdata/1/{participant_id}_GSR.csv')
        psy_df = pd.read_csv(f'../stdata/1/{participant_id}_PSY.csv')
    except FileNotFoundError:
        print(f"Files for participant {participant_id} not found. Skipping.")
        return None

    # --- 2. Clean and Prepare Timestamps ---
    eeg_df['UnixTime'] = pd.to_numeric(eeg_df['UnixTime'], errors='coerce')
    gsr_df['UnixTime'] = pd.to_numeric(gsr_df['UnixTime'], errors='coerce')
    psy_df['routineStart'] = pd.to_numeric(psy_df['routineStart'], errors='coerce')
    psy_df['routineEnd'] = pd.to_numeric(psy_df['routineEnd'], errors='coerce')

    eeg_df.dropna(subset=['UnixTime'], inplace=True)
    gsr_df.dropna(subset=['UnixTime'], inplace=True)
    psy_df.dropna(subset=['routineStart', 'routineEnd'], inplace=True)

    # --- 3. Create Cognitive Load Labels ---
    label_mapping = {1: 0, 2: 1, 3: 2} # Low, Medium, High
    psy_df['CognitiveLoad'] = psy_df['Category'].map(label_mapping)

    # --- 4. Feature Extraction Loop ---
    all_task_features = []

    for _, task in psy_df.iterrows():
        start_time = task['routineStart']
        end_time = task['routineEnd']

        # Slice the data for the current task
        eeg_slice = eeg_df[(eeg_df['UnixTime'] >= start_time) & (eeg_df['UnixTime'] <= end_time)]
        gsr_slice = gsr_df[(gsr_df['UnixTime'] >= start_time) & (gsr_df['UnixTime'] <= end_time)]

        if eeg_slice.empty or gsr_slice.empty:
            continue

        # --- EEG Feature Engineering ---
        features = {
            'Participant': participant_id,
            'TaskKey': task['Key'],
            'CognitiveLoad': task['CognitiveLoad']
        }
        
        # Define the brainwave bands and their corresponding columns
        bands = ['Delta', 'Theta', 'Alpha', 'Beta', 'Gamma']
        electrodes = ['TP9', 'AF7', 'AF8', 'TP10']
        
        # Calculate mean and variance for each band
        for band in bands:
            band_cols = [f'{band}_{elec}' for elec in electrodes]
            # Take the mean across electrodes first, then across time
            features[f'EEG_{band}_Mean'] = eeg_slice[band_cols].mean(axis=1).mean()
            features[f'EEG_{band}_Var'] = eeg_slice[band_cols].mean(axis=1).var()

        # Calculate workload ratios
        theta_mean = eeg_slice[[f'Theta_{e}' for e in electrodes]].mean(axis=1).mean()
        alpha_mean = eeg_slice[[f'Alpha_{e}' for e in electrodes]].mean(axis=1).mean()
        beta_mean = eeg_slice[[f'Beta_{e}' for e in electrodes]].mean(axis=1).mean()
        
        # Add a small epsilon to avoid division by zero
        epsilon = 1e-6 
        features['EEG_Theta_Alpha_Ratio'] = theta_mean / (alpha_mean + epsilon)
        features['EEG_Theta_Beta_Ratio'] = theta_mean / (beta_mean + epsilon)

        # --- GSR Feature Engineering ---
        gsr_col = 'GSR Conductance CAL'
        features['GSR_Mean'] = gsr_slice[gsr_col].mean()
        features['GSR_Var'] = gsr_slice[gsr_col].var()
        
        all_task_features.append(features)

    return pd.DataFrame(all_task_features)

# --- Main Execution ---
print("Processing participant 1...")
features_df = create_feature_dataset(1)

if features_df is not None:
    print("Successfully created feature dataset!")
    print("Shape of the dataset:", features_df.shape)
    print("\nFirst 5 rows of the final feature table:")
    print(features_df.head())
    
    # Save the final dataset to a CSV file for the next step
    features_df.to_csv('../data/participant_1_features.csv', index=False)
    print("\nSaved features to 'participant_1_features.csv'")

Processing participant 1...
Successfully created feature dataset!
Shape of the dataset: (40, 17)

First 5 rows of the final feature table:
   Participant TaskKey  CognitiveLoad  EEG_Delta_Mean  EEG_Delta_Var  \
0            1   1spl1              0        0.239537       0.021580
1            1   1spl2              0        0.725022       0.063404
2            1  1Item1              0        0.842528       0.102015
3            1  1Item2              0        0.843536       0.079742
4            1  1Item3              0        0.797471       0.029748

   EEG_Theta_Mean  EEG_Theta_Var  EEG_Alpha_Mean  EEG_Alpha_Var  \
0        0.176614       0.005094        0.414501       0.009543
1        0.417921       0.059792        0.597913       0.051915
2        0.515361       0.082573        0.674078       0.027990
3        0.521588       0.021623        0.717120       0.019851
4        0.449036       0.024646        0.638049       0.022884

   EEG_Beta_Mean  EEG_Beta_Var  EEG_Gamma_Mean  EEG_Gamma_Var  \
0       0.267745      0.002339       -0.207820       0.002331
1       0.326772      0.006033       -0.053515       0.013247
2       0.363511      0.003687       -0.104016       0.002081
3       0.298959      0.001725       -0.142325       0.001504
4       0.308217      0.003499       -0.156758       0.003140

   EEG_Theta_Alpha_Ratio  EEG_Theta_Beta_Ratio   GSR_Mean   GSR_Var
0               0.426086              0.659631  18.194721  1.962237
1               0.698964              1.278932  18.067476  0.168139
2               0.764541              1.417727  17.455089  0.056395
3               0.727336              1.744676  17.686396  0.438683
4               0.703763              1.456875  16.484022  0.093003

Saved features to 'participant_1_features.csv'

Feature Extraction from EEG, GSR, and PSY Data
This code processes physiological data for a participant and generates features for further analysis.
Steps:

1. **Load Data**  
   - Reads three CSV files for a participant: EEG, GSR, and PSY.  
   - Files are stored in `../stdata/1/`.

2. **Clean Timestamps**  
   - Converts timestamps to numeric values.  
   - Drops rows with missing values.

3. **Create Cognitive Load Labels**  
   - Maps the `Category` column from PSY data:  
     - 1 → Low (0)  
     - 2 → Medium (1)  
     - 3 → High (2)

4. **Feature Extraction**  
   - For each task (from PSY start and end times), slices EEG and GSR data.  
   - EEG features: mean and variance of Delta, Theta, Alpha, Beta, Gamma bands.  
   - Ratios: Theta/Alpha and Theta/Beta.  
   - GSR features: mean and variance.

5. **Save Results**  
   - Stores all features in a dataframe.  
   - Saves the output as `../data/participant_1_features.csv`.
Summary
The code prepares a structured dataset by combining EEG, GSR, and PSY data, extracting statistical features, labeling tasks with cognitive load, and saving the results for further analysis.

In [ ]:
SRC_ROOT = Path("stdata")   
DST_ROOT = Path("data")     
CATEGORIES = ["EEG", "GSR", "PSY"]

for cat in CATEGORIES:
    (DST_ROOT / cat).mkdir(parents=True, exist_ok=True)

for i in range(1, 39):  
    src_folder = SRC_ROOT / str(i)

    if not src_folder.exists():
        print(f"Skipping: source folder not found -> {src_folder}")
        continue

    for cat in CATEGORIES:
        filename = f"{i}_{cat}.csv"
        src_file = src_folder / filename
        dst_file = DST_ROOT / cat / filename

        if not src_file.exists():
            print(f"Skipping (file not found): {src_file}")
            continue


        shutil.copy2(src_file, dst_file)
        print(f"Copied: {src_file} -> {dst_file}")

print("All done.")

Copied: stdata\1\1_EEG.csv -> data\EEG\1_EEG.csv
Copied: stdata\1\1_GSR.csv -> data\GSR\1_GSR.csv
Copied: stdata\1\1_PSY.csv -> data\PSY\1_PSY.csv
Copied: stdata\2\2_EEG.csv -> data\EEG\2_EEG.csv
Copied: stdata\2\2_GSR.csv -> data\GSR\2_GSR.csv
Copied: stdata\2\2_PSY.csv -> data\PSY\2_PSY.csv
Copied: stdata\3\3_EEG.csv -> data\EEG\3_EEG.csv
Copied: stdata\3\3_GSR.csv -> data\GSR\3_GSR.csv
Copied: stdata\3\3_PSY.csv -> data\PSY\3_PSY.csv
Copied: stdata\4\4_EEG.csv -> data\EEG\4_EEG.csv
Copied: stdata\4\4_GSR.csv -> data\GSR\4_GSR.csv
Copied: stdata\4\4_PSY.csv -> data\PSY\4_PSY.csv
Copied: stdata\5\5_EEG.csv -> data\EEG\5_EEG.csv
Copied: stdata\5\5_GSR.csv -> data\GSR\5_GSR.csv
Copied: stdata\5\5_PSY.csv -> data\PSY\5_PSY.csv
Copied: stdata\6\6_EEG.csv -> data\EEG\6_EEG.csv
Copied: stdata\6\6_GSR.csv -> data\GSR\6_GSR.csv
Copied: stdata\6\6_PSY.csv -> data\PSY\6_PSY.csv
Copied: stdata\7\7_EEG.csv -> data\EEG\7_EEG.csv
Copied: stdata\7\7_GSR.csv -> data\GSR\7_GSR.csv
Copied: stdata\7\7_PSY.csv -> data\PSY\7_PSY.csv
Copied: stdata\8\8_EEG.csv -> data\EEG\8_EEG.csv
Copied: stdata\8\8_GSR.csv -> data\GSR\8_GSR.csv
Copied: stdata\8\8_PSY.csv -> data\PSY\8_PSY.csv
Copied: stdata\9\9_EEG.csv -> data\EEG\9_EEG.csv
Copied: stdata\9\9_GSR.csv -> data\GSR\9_GSR.csv
Copied: stdata\9\9_PSY.csv -> data\PSY\9_PSY.csv
Copied: stdata\10\10_EEG.csv -> data\EEG\10_EEG.csv
Copied: stdata\10\10_GSR.csv -> data\GSR\10_GSR.csv
Copied: stdata\10\10_PSY.csv -> data\PSY\10_PSY.csv
Copied: stdata\11\11_EEG.csv -> data\EEG\11_EEG.csv
Copied: stdata\11\11_GSR.csv -> data\GSR\11_GSR.csv
Copied: stdata\11\11_PSY.csv -> data\PSY\11_PSY.csv
Copied: stdata\12\12_EEG.csv -> data\EEG\12_EEG.csv
Copied: stdata\12\12_GSR.csv -> data\GSR\12_GSR.csv
Copied: stdata\12\12_PSY.csv -> data\PSY\12_PSY.csv
Copied: stdata\13\13_EEG.csv -> data\EEG\13_EEG.csv
Copied: stdata\13\13_GSR.csv -> data\GSR\13_GSR.csv
Copied: stdata\13\13_PSY.csv -> data\PSY\13_PSY.csv
Copied: stdata\14\14_EEG.csv -> data\EEG\14_EEG.csv
Copied: stdata\14\14_GSR.csv -> data\GSR\14_GSR.csv
Copied: stdata\14\14_PSY.csv -> data\PSY\14_PSY.csv
Copied: stdata\15\15_EEG.csv -> data\EEG\15_EEG.csv
Copied: stdata\15\15_GSR.csv -> data\GSR\15_GSR.csv
Copied: stdata\15\15_PSY.csv -> data\PSY\15_PSY.csv
Copied: stdata\16\16_EEG.csv -> data\EEG\16_EEG.csv
Copied: stdata\16\16_GSR.csv -> data\GSR\16_GSR.csv
Copied: stdata\16\16_PSY.csv -> data\PSY\16_PSY.csv
Copied: stdata\17\17_EEG.csv -> data\EEG\17_EEG.csv
Copied: stdata\17\17_GSR.csv -> data\GSR\17_GSR.csv
Copied: stdata\17\17_PSY.csv -> data\PSY\17_PSY.csv
Copied: stdata\18\18_EEG.csv -> data\EEG\18_EEG.csv
Copied: stdata\18\18_GSR.csv -> data\GSR\18_GSR.csv
Copied: stdata\18\18_PSY.csv -> data\PSY\18_PSY.csv
Copied: stdata\19\19_EEG.csv -> data\EEG\19_EEG.csv
Copied: stdata\19\19_GSR.csv -> data\GSR\19_GSR.csv
Copied: stdata\19\19_PSY.csv -> data\PSY\19_PSY.csv
Copied: stdata\20\20_EEG.csv -> data\EEG\20_EEG.csv
Copied: stdata\20\20_GSR.csv -> data\GSR\20_GSR.csv
Copied: stdata\20\20_PSY.csv -> data\PSY\20_PSY.csv
Copied: stdata\21\21_EEG.csv -> data\EEG\21_EEG.csv
Copied: stdata\21\21_GSR.csv -> data\GSR\21_GSR.csv
Copied: stdata\21\21_PSY.csv -> data\PSY\21_PSY.csv
Copied: stdata\22\22_EEG.csv -> data\EEG\22_EEG.csv
Copied: stdata\22\22_GSR.csv -> data\GSR\22_GSR.csv
Copied: stdata\22\22_PSY.csv -> data\PSY\22_PSY.csv
Copied: stdata\23\23_EEG.csv -> data\EEG\23_EEG.csv
Copied: stdata\23\23_GSR.csv -> data\GSR\23_GSR.csv
Copied: stdata\23\23_PSY.csv -> data\PSY\23_PSY.csv
Copied: stdata\24\24_EEG.csv -> data\EEG\24_EEG.csv
Copied: stdata\24\24_GSR.csv -> data\GSR\24_GSR.csv
Copied: stdata\24\24_PSY.csv -> data\PSY\24_PSY.csv
Copied: stdata\25\25_EEG.csv -> data\EEG\25_EEG.csv
Copied: stdata\25\25_GSR.csv -> data\GSR\25_GSR.csv
Copied: stdata\25\25_PSY.csv -> data\PSY\25_PSY.csv
Copied: stdata\26\26_EEG.csv -> data\EEG\26_EEG.csv
Copied: stdata\26\26_GSR.csv -> data\GSR\26_GSR.csv
Copied: stdata\26\26_PSY.csv -> data\PSY\26_PSY.csv
Copied: stdata\27\27_EEG.csv -> data\EEG\27_EEG.csv
Copied: stdata\27\27_GSR.csv -> data\GSR\27_GSR.csv
Copied: stdata\27\27_PSY.csv -> data\PSY\27_PSY.csv
Copied: stdata\28\28_EEG.csv -> data\EEG\28_EEG.csv
Copied: stdata\28\28_GSR.csv -> data\GSR\28_GSR.csv
Copied: stdata\28\28_PSY.csv -> data\PSY\28_PSY.csv
Copied: stdata\29\29_EEG.csv -> data\EEG\29_EEG.csv
Copied: stdata\29\29_GSR.csv -> data\GSR\29_GSR.csv
Copied: stdata\29\29_PSY.csv -> data\PSY\29_PSY.csv
Copied: stdata\30\30_EEG.csv -> data\EEG\30_EEG.csv
Copied: stdata\30\30_GSR.csv -> data\GSR\30_GSR.csv
Copied: stdata\30\30_PSY.csv -> data\PSY\30_PSY.csv
Copied: stdata\31\31_EEG.csv -> data\EEG\31_EEG.csv
Copied: stdata\31\31_GSR.csv -> data\GSR\31_GSR.csv
Copied: stdata\31\31_PSY.csv -> data\PSY\31_PSY.csv
Copied: stdata\32\32_EEG.csv -> data\EEG\32_EEG.csv
Copied: stdata\32\32_GSR.csv -> data\GSR\32_GSR.csv
Copied: stdata\32\32_PSY.csv -> data\PSY\32_PSY.csv
Copied: stdata\33\33_EEG.csv -> data\EEG\33_EEG.csv
Copied: stdata\33\33_GSR.csv -> data\GSR\33_GSR.csv
Copied: stdata\33\33_PSY.csv -> data\PSY\33_PSY.csv
Copied: stdata\34\34_EEG.csv -> data\EEG\34_EEG.csv
Copied: stdata\34\34_GSR.csv -> data\GSR\34_GSR.csv
Copied: stdata\34\34_PSY.csv -> data\PSY\34_PSY.csv
Copied: stdata\35\35_EEG.csv -> data\EEG\35_EEG.csv
Copied: stdata\35\35_GSR.csv -> data\GSR\35_GSR.csv
Copied: stdata\35\35_PSY.csv -> data\PSY\35_PSY.csv
Copied: stdata\36\36_EEG.csv -> data\EEG\36_EEG.csv
Copied: stdata\36\36_GSR.csv -> data\GSR\36_GSR.csv
Copied: stdata\36\36_PSY.csv -> data\PSY\36_PSY.csv
Copied: stdata\37\37_EEG.csv -> data\EEG\37_EEG.csv
Copied: stdata\37\37_GSR.csv -> data\GSR\37_GSR.csv
Copied: stdata\37\37_PSY.csv -> data\PSY\37_PSY.csv
Copied: stdata\38\38_EEG.csv -> data\EEG\38_EEG.csv
Copied: stdata\38\38_GSR.csv -> data\GSR\38_GSR.csv
Copied: stdata\38\38_PSY.csv -> data\PSY\38_PSY.csv
All done.

>This code organizes participant data files into separate folders.  
It creates `EEG`, `GSR`, and `PSY` directories inside `data/`.  
For each participant (1 to 38), it checks if the source folder exists.  
If the CSV files are found, they are copied from `stdata` into the corresponding category folder under `data`.  
Missing folders or files are skipped with a message.  
Finally, it prints confirmation after copying all available files.

In [ ]:
# Paths
DATA_ROOT = Path("data")
EEG_PATH = DATA_ROOT / "EEG"
GSR_PATH = DATA_ROOT / "GSR"
PSY_PATH = DATA_ROOT / "PSY"

# Columns to keep
EEG_KEEP = [
    "Delta_TP9","Delta_AF7","Delta_AF8","Delta_TP10",
    "Theta_TP9","Theta_AF7","Theta_AF8","Theta_TP10",
    "Alpha_TP9","Alpha_AF7","Alpha_AF8","Alpha_TP10",
    "Beta_TP9","Beta_AF7","Beta_AF8","Beta_TP10",
    "Gamma_TP9","Gamma_AF7","Gamma_AF8","Gamma_TP10"
]

GSR_KEEP = ["GSR Resistance CAL", "GSR Conductance CAL"]

PSY_KEEP = ["routineStart", "routineEnd", "Difficulty"]

# ---- EEG ----
for i in range(1, 39):
    file = EEG_PATH / f"{i}_EEG.csv"
    if file.exists():
        df = pd.read_csv(file)
        df = df[EEG_KEEP]  # keep only required columns
        df.to_csv(file, index=False)

# ---- GSR ----
for i in range(1, 39):
    file = GSR_PATH / f"{i}_GSR.csv"
    if file.exists():
        df = pd.read_csv(file)
        df = df[GSR_KEEP]
        df.to_csv(file, index=False)

# ---- PSY ----
for i in range(1, 39):
    file = PSY_PATH / f"{i}_PSY.csv"
    if file.exists():
        df = pd.read_csv(file)
        df = df[PSY_KEEP]
        df.to_csv(file, index=False)

print("Columns dropped, only required columns saved back.")

Columns dropped, only required columns saved back.

>This code cleans EEG, GSR, and PSY data files for 38 participants.  
It defines which columns to keep for each type of data.  
For every participant file, it loads the CSV, keeps only the selected columns, and saves it back.  
This ensures only the necessary EEG bands, GSR measures, and PSY task info remain.  
Finally, it confirms that unwanted columns have been removed.

In [9]:
# Root path
DATA_ROOT = Path("..") / "data"  

# Folders
EEG_PATH = DATA_ROOT / "EEG"
GSR_PATH = DATA_ROOT / "GSR"
PSY_PATH = DATA_ROOT / "PSY"

# Columns to keep
EEG_KEEP = [
    "Delta_TP9","Delta_AF7","Delta_AF8","Delta_TP10",
    "Theta_TP9","Theta_AF7","Theta_AF8","Theta_TP10",
    "Alpha_TP9","Alpha_AF7","Alpha_AF8","Alpha_TP10",
    "Beta_TP9","Beta_AF7","Beta_AF8","Beta_TP10",
    "Gamma_TP9","Gamma_AF7","Gamma_AF8","Gamma_TP10"
]

GSR_KEEP = ["GSR Resistance CAL", "GSR Conductance CAL"]

PSY_KEEP = ["routineStart", "routineEnd", "Difficulty"]

# ---- EEG ----
for i in range(1, 39):
    file = EEG_PATH / f"{i}_EEG.csv"
    if file.exists():
        df = pd.read_csv(file)
        df.columns = df.columns.str.strip()  # remove extra spaces
        df = df[EEG_KEEP]                    # keep only required columns
        df.to_csv(file, index=False)
        print(f"Processed {file}")

# ---- GSR ----
for i in range(1, 39):
    file = GSR_PATH / f"{i}_GSR.csv"
    if file.exists():
        df = pd.read_csv(file)
        df.columns = df.columns.str.strip()
        df = df[GSR_KEEP]
        df.to_csv(file, index=False)
        print(f"Processed {file}")

# ---- PSY ----
for i in range(1, 39):
    file = PSY_PATH / f"{i}_PSY.csv"
    if file.exists():
        df = pd.read_csv(file)
        df.columns = df.columns.str.strip()
        df = df[PSY_KEEP]
        df.to_csv(file, index=False)
        print(f"Processed {file}")

print("All EEG, GSR, PSY files saved (extra columns dropped).")

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\1_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\2_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\3_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\4_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\5_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\6_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\7_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\8_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\9_EEG.csv
Processed ..\data\EEG\10_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\11_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\12_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\13_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\14_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\15_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\16_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\17_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\18_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\19_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\20_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\21_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\22_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\23_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\24_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\25_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\26_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\27_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\28_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\29_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\30_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\31_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\32_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\33_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\34_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\35_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\36_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\37_EEG.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:26: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\EEG\38_EEG.csv
Processed ..\data\GSR\1_GSR.csv
Processed ..\data\GSR\2_GSR.csv
Processed ..\data\GSR\3_GSR.csv
Processed ..\data\GSR\4_GSR.csv
Processed ..\data\GSR\5_GSR.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:36: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\GSR\6_GSR.csv
Processed ..\data\GSR\7_GSR.csv
Processed ..\data\GSR\8_GSR.csv
Processed ..\data\GSR\9_GSR.csv
Processed ..\data\GSR\10_GSR.csv
Processed ..\data\GSR\11_GSR.csv
Processed ..\data\GSR\12_GSR.csv
Processed ..\data\GSR\13_GSR.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:36: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\GSR\14_GSR.csv
Processed ..\data\GSR\15_GSR.csv
Processed ..\data\GSR\16_GSR.csv
Processed ..\data\GSR\17_GSR.csv
Processed ..\data\GSR\18_GSR.csv
Processed ..\data\GSR\19_GSR.csv
Processed ..\data\GSR\20_GSR.csv
Processed ..\data\GSR\21_GSR.csv
Processed ..\data\GSR\22_GSR.csv
Processed ..\data\GSR\23_GSR.csv
Processed ..\data\GSR\24_GSR.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:36: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\GSR\25_GSR.csv

C:\Users\SANIYA\AppData\Local\Temp\ipykernel_11880\1039098871.py:36: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Processed ..\data\GSR\26_GSR.csv
Processed ..\data\GSR\27_GSR.csv
Processed ..\data\GSR\28_GSR.csv
Processed ..\data\GSR\29_GSR.csv
Processed ..\data\GSR\30_GSR.csv
Processed ..\data\GSR\31_GSR.csv
Processed ..\data\GSR\32_GSR.csv
Processed ..\data\GSR\33_GSR.csv
Processed ..\data\GSR\34_GSR.csv
Processed ..\data\GSR\35_GSR.csv
Processed ..\data\GSR\36_GSR.csv
Processed ..\data\GSR\37_GSR.csv
Processed ..\data\GSR\38_GSR.csv
Processed ..\data\PSY\1_PSY.csv
Processed ..\data\PSY\2_PSY.csv
Processed ..\data\PSY\3_PSY.csv
Processed ..\data\PSY\4_PSY.csv
Processed ..\data\PSY\5_PSY.csv
Processed ..\data\PSY\6_PSY.csv
Processed ..\data\PSY\7_PSY.csv
Processed ..\data\PSY\8_PSY.csv
Processed ..\data\PSY\9_PSY.csv
Processed ..\data\PSY\10_PSY.csv
Processed ..\data\PSY\11_PSY.csv
Processed ..\data\PSY\12_PSY.csv
Processed ..\data\PSY\13_PSY.csv
Processed ..\data\PSY\14_PSY.csv
Processed ..\data\PSY\15_PSY.csv
Processed ..\data\PSY\16_PSY.csv
Processed ..\data\PSY\17_PSY.csv
Processed ..\data\PSY\18_PSY.csv
Processed ..\data\PSY\19_PSY.csv
Processed ..\data\PSY\20_PSY.csv
Processed ..\data\PSY\21_PSY.csv
Processed ..\data\PSY\22_PSY.csv
Processed ..\data\PSY\23_PSY.csv
Processed ..\data\PSY\24_PSY.csv
Processed ..\data\PSY\25_PSY.csv
Processed ..\data\PSY\26_PSY.csv
Processed ..\data\PSY\27_PSY.csv
Processed ..\data\PSY\28_PSY.csv
Processed ..\data\PSY\29_PSY.csv
Processed ..\data\PSY\30_PSY.csv
Processed ..\data\PSY\31_PSY.csv
Processed ..\data\PSY\32_PSY.csv
Processed ..\data\PSY\33_PSY.csv
Processed ..\data\PSY\34_PSY.csv
Processed ..\data\PSY\35_PSY.csv
Processed ..\data\PSY\36_PSY.csv
Processed ..\data\PSY\37_PSY.csv
Processed ..\data\PSY\38_PSY.csv
All EEG, GSR, PSY files saved (extra columns dropped).

In [13]:
folders = {
    "EEG": "../data/EEG",
    "GSR": "../data/GSR",
    "PSY": "../data/PSY"
}

num_files = 38

for folder_name, folder_path in folders.items():
    if not os.path.exists(folder_path):
        print(f"[WARN] Folder not found: {folder_path}")
        continue

    print(f"\n=== Checking folder: {folder_name} ===")

    for i in range(1, num_files + 1):
        file_name = f"{i}_{folder_name}.csv"
        file_path = os.path.join(folder_path, file_name)
        
        if not os.path.exists(file_path):
            print(f"[WARN] File not found: {file_name}")
            continue
        
        try:
            df = pd.read_csv(file_path)
        except Exception as e:
            print(f"Error reading {file_name}: {e}")
            continue
        
        # Count nulls per column
        null_counts = df.isnull().sum().reset_index()
        null_counts.columns = ["Column Name", "Null Count"]
        
        print(f"\n{file_name} -")
        display(null_counts)
        html_table = null_counts.to_html(index=False)

=== Checking folder: EEG ===

1_EEG.csv -

   Column Name  Null Count
0    Delta_TP9          12
1    Delta_AF7          12
2    Delta_AF8          12
3   Delta_TP10          12
4    Theta_TP9          12
5    Theta_AF7          12
6    Theta_AF8          12
7   Theta_TP10          12
8    Alpha_TP9          12
9    Alpha_AF7          12
10   Alpha_AF8          12
11  Alpha_TP10          12
12    Beta_TP9          12
13    Beta_AF7          12
14    Beta_AF8          12
15   Beta_TP10          12
16   Gamma_TP9          12
17   Gamma_AF7          12
18   Gamma_AF8          12
19  Gamma_TP10          12

2_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         209
1    Delta_AF7         209
2    Delta_AF8         209
3   Delta_TP10         209
4    Theta_TP9         209
5    Theta_AF7         209
6    Theta_AF8         209
7   Theta_TP10         209
8    Alpha_TP9         209
9    Alpha_AF7         209
10   Alpha_AF8         209
11  Alpha_TP10         209
12    Beta_TP9         209
13    Beta_AF7         209
14    Beta_AF8         209
15   Beta_TP10         209
16   Gamma_TP9         209
17   Gamma_AF7         209
18   Gamma_AF8         209
19  Gamma_TP10         209

3_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         318
1    Delta_AF7         318
2    Delta_AF8         318
3   Delta_TP10         318
4    Theta_TP9         318
5    Theta_AF7         318
6    Theta_AF8         318
7   Theta_TP10         318
8    Alpha_TP9         318
9    Alpha_AF7         318
10   Alpha_AF8         318
11  Alpha_TP10         318
12    Beta_TP9         318
13    Beta_AF7         318
14    Beta_AF8         318
15   Beta_TP10         318
16   Gamma_TP9         318
17   Gamma_AF7         318
18   Gamma_AF8         318
19  Gamma_TP10         318

4_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         142
1    Delta_AF7         142
2    Delta_AF8         142
3   Delta_TP10         142
4    Theta_TP9         142
5    Theta_AF7         142
6    Theta_AF8         142
7   Theta_TP10         142
8    Alpha_TP9         142
9    Alpha_AF7         142
10   Alpha_AF8         142
11  Alpha_TP10         142
12    Beta_TP9         142
13    Beta_AF7         142
14    Beta_AF8         142
15   Beta_TP10         142
16   Gamma_TP9         142
17   Gamma_AF7         142
18   Gamma_AF8         142
19  Gamma_TP10         142

5_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         579
1    Delta_AF7         579
2    Delta_AF8         579
3   Delta_TP10         579
4    Theta_TP9         579
5    Theta_AF7         579
6    Theta_AF8         579
7   Theta_TP10         579
8    Alpha_TP9         579
9    Alpha_AF7         579
10   Alpha_AF8         579
11  Alpha_TP10         579
12    Beta_TP9         579
13    Beta_AF7         579
14    Beta_AF8         579
15   Beta_TP10         579
16   Gamma_TP9         579
17   Gamma_AF7         579
18   Gamma_AF8         579
19  Gamma_TP10         579

6_EEG.csv -

   Column Name  Null Count
0    Delta_TP9          64
1    Delta_AF7          64
2    Delta_AF8          64
3   Delta_TP10          64
4    Theta_TP9          64
5    Theta_AF7          64
6    Theta_AF8          64
7   Theta_TP10          64
8    Alpha_TP9          64
9    Alpha_AF7          64
10   Alpha_AF8          64
11  Alpha_TP10          64
12    Beta_TP9          64
13    Beta_AF7          64
14    Beta_AF8          64
15   Beta_TP10          64
16   Gamma_TP9          64
17   Gamma_AF7          64
18   Gamma_AF8          64
19  Gamma_TP10          64

7_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         438
1    Delta_AF7         438
2    Delta_AF8         438
3   Delta_TP10         438
4    Theta_TP9         438
5    Theta_AF7         438
6    Theta_AF8         438
7   Theta_TP10         438
8    Alpha_TP9         438
9    Alpha_AF7         438
10   Alpha_AF8         438
11  Alpha_TP10         438
12    Beta_TP9         438
13    Beta_AF7         438
14    Beta_AF8         438
15   Beta_TP10         438
16   Gamma_TP9         438
17   Gamma_AF7         438
18   Gamma_AF8         438
19  Gamma_TP10         438

8_EEG.csv -

   Column Name  Null Count
0    Delta_TP9          82
1    Delta_AF7          82
2    Delta_AF8          82
3   Delta_TP10          82
4    Theta_TP9          82
5    Theta_AF7          82
6    Theta_AF8          82
7   Theta_TP10          82
8    Alpha_TP9          82
9    Alpha_AF7          82
10   Alpha_AF8          82
11  Alpha_TP10          82
12    Beta_TP9          82
13    Beta_AF7          82
14    Beta_AF8          82
15   Beta_TP10          82
16   Gamma_TP9          82
17   Gamma_AF7          82
18   Gamma_AF8          82
19  Gamma_TP10          82

9_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         392
1    Delta_AF7         392
2    Delta_AF8         392
3   Delta_TP10         392
4    Theta_TP9         392
5    Theta_AF7         392
6    Theta_AF8         392
7   Theta_TP10         392
8    Alpha_TP9         392
9    Alpha_AF7         392
10   Alpha_AF8         392
11  Alpha_TP10         392
12    Beta_TP9         392
13    Beta_AF7         392
14    Beta_AF8         392
15   Beta_TP10         392
16   Gamma_TP9         392
17   Gamma_AF7         392
18   Gamma_AF8         392
19  Gamma_TP10         392

10_EEG.csv -

   Column Name  Null Count
0    Delta_TP9           0
1    Delta_AF7           0
2    Delta_AF8           0
3   Delta_TP10           0
4    Theta_TP9           0
5    Theta_AF7           0
6    Theta_AF8           0
7   Theta_TP10           0
8    Alpha_TP9           0
9    Alpha_AF7           0
10   Alpha_AF8           0
11  Alpha_TP10           0
12    Beta_TP9           0
13    Beta_AF7           0
14    Beta_AF8           0
15   Beta_TP10           0
16   Gamma_TP9           0
17   Gamma_AF7           0
18   Gamma_AF8           0
19  Gamma_TP10           0

11_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         217
1    Delta_AF7         217
2    Delta_AF8         217
3   Delta_TP10         217
4    Theta_TP9         217
5    Theta_AF7         217
6    Theta_AF8         217
7   Theta_TP10         217
8    Alpha_TP9         217
9    Alpha_AF7         217
10   Alpha_AF8         217
11  Alpha_TP10         217
12    Beta_TP9         217
13    Beta_AF7         217
14    Beta_AF8         217
15   Beta_TP10         217
16   Gamma_TP9         217
17   Gamma_AF7         217
18   Gamma_AF8         217
19  Gamma_TP10         217

12_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         603
1    Delta_AF7         603
2    Delta_AF8         603
3   Delta_TP10         603
4    Theta_TP9         603
5    Theta_AF7         603
6    Theta_AF8         603
7   Theta_TP10         603
8    Alpha_TP9         603
9    Alpha_AF7         603
10   Alpha_AF8         603
11  Alpha_TP10         603
12    Beta_TP9         603
13    Beta_AF7         603
14    Beta_AF8         603
15   Beta_TP10         603
16   Gamma_TP9         603
17   Gamma_AF7         603
18   Gamma_AF8         603
19  Gamma_TP10         603

13_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         383
1    Delta_AF7         383
2    Delta_AF8         383
3   Delta_TP10         383
4    Theta_TP9         383
5    Theta_AF7         383
6    Theta_AF8         383
7   Theta_TP10         383
8    Alpha_TP9         383
9    Alpha_AF7         383
10   Alpha_AF8         383
11  Alpha_TP10         383
12    Beta_TP9         383
13    Beta_AF7         383
14    Beta_AF8         383
15   Beta_TP10         383
16   Gamma_TP9         383
17   Gamma_AF7         383
18   Gamma_AF8         383
19  Gamma_TP10         383

14_EEG.csv -

   Column Name  Null Count
0    Delta_TP9          56
1    Delta_AF7          56
2    Delta_AF8          56
3   Delta_TP10          56
4    Theta_TP9          56
5    Theta_AF7          56
6    Theta_AF8          56
7   Theta_TP10          56
8    Alpha_TP9          56
9    Alpha_AF7          56
10   Alpha_AF8          56
11  Alpha_TP10          56
12    Beta_TP9          56
13    Beta_AF7          56
14    Beta_AF8          56
15   Beta_TP10          56
16   Gamma_TP9          56
17   Gamma_AF7          56
18   Gamma_AF8          56
19  Gamma_TP10          56

15_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         182
1    Delta_AF7         182
2    Delta_AF8         182
3   Delta_TP10         182
4    Theta_TP9         182
5    Theta_AF7         182
6    Theta_AF8         182
7   Theta_TP10         182
8    Alpha_TP9         182
9    Alpha_AF7         182
10   Alpha_AF8         182
11  Alpha_TP10         182
12    Beta_TP9         182
13    Beta_AF7         182
14    Beta_AF8         182
15   Beta_TP10         182
16   Gamma_TP9         182
17   Gamma_AF7         182
18   Gamma_AF8         182
19  Gamma_TP10         182

16_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         191
1    Delta_AF7         191
2    Delta_AF8         191
3   Delta_TP10         191
4    Theta_TP9         191
5    Theta_AF7         191
6    Theta_AF8         191
7   Theta_TP10         191
8    Alpha_TP9         191
9    Alpha_AF7         191
10   Alpha_AF8         191
11  Alpha_TP10         191
12    Beta_TP9         191
13    Beta_AF7         191
14    Beta_AF8         191
15   Beta_TP10         191
16   Gamma_TP9         191
17   Gamma_AF7         191
18   Gamma_AF8         191
19  Gamma_TP10         191

17_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         238
1    Delta_AF7         238
2    Delta_AF8         238
3   Delta_TP10         238
4    Theta_TP9         238
5    Theta_AF7         238
6    Theta_AF8         238
7   Theta_TP10         238
8    Alpha_TP9         238
9    Alpha_AF7         238
10   Alpha_AF8         238
11  Alpha_TP10         238
12    Beta_TP9         238
13    Beta_AF7         238
14    Beta_AF8         238
15   Beta_TP10         238
16   Gamma_TP9         238
17   Gamma_AF7         238
18   Gamma_AF8         238
19  Gamma_TP10         238

18_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         443
1    Delta_AF7         443
2    Delta_AF8         443
3   Delta_TP10         443
4    Theta_TP9         443
5    Theta_AF7         443
6    Theta_AF8         443
7   Theta_TP10         443
8    Alpha_TP9         443
9    Alpha_AF7         443
10   Alpha_AF8         443
11  Alpha_TP10         443
12    Beta_TP9         443
13    Beta_AF7         443
14    Beta_AF8         443
15   Beta_TP10         443
16   Gamma_TP9         443
17   Gamma_AF7         443
18   Gamma_AF8         443
19  Gamma_TP10         443

19_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         228
1    Delta_AF7         228
2    Delta_AF8         228
3   Delta_TP10         228
4    Theta_TP9         228
5    Theta_AF7         228
6    Theta_AF8         228
7   Theta_TP10         228
8    Alpha_TP9         228
9    Alpha_AF7         228
10   Alpha_AF8         228
11  Alpha_TP10         228
12    Beta_TP9         228
13    Beta_AF7         228
14    Beta_AF8         228
15   Beta_TP10         228
16   Gamma_TP9         228
17   Gamma_AF7         228
18   Gamma_AF8         228
19  Gamma_TP10         228

20_EEG.csv -

   Column Name  Null Count
0    Delta_TP9          42
1    Delta_AF7          42
2    Delta_AF8          42
3   Delta_TP10          42
4    Theta_TP9          42
5    Theta_AF7          42
6    Theta_AF8          42
7   Theta_TP10          42
8    Alpha_TP9          42
9    Alpha_AF7          42
10   Alpha_AF8          42
11  Alpha_TP10          42
12    Beta_TP9          42
13    Beta_AF7          42
14    Beta_AF8          42
15   Beta_TP10          42
16   Gamma_TP9          42
17   Gamma_AF7          42
18   Gamma_AF8          42
19  Gamma_TP10          42

21_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         221
1    Delta_AF7         221
2    Delta_AF8         221
3   Delta_TP10         221
4    Theta_TP9         221
5    Theta_AF7         221
6    Theta_AF8         221
7   Theta_TP10         221
8    Alpha_TP9         221
9    Alpha_AF7         221
10   Alpha_AF8         221
11  Alpha_TP10         221
12    Beta_TP9         221
13    Beta_AF7         221
14    Beta_AF8         221
15   Beta_TP10         221
16   Gamma_TP9         221
17   Gamma_AF7         221
18   Gamma_AF8         221
19  Gamma_TP10         221

22_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         312
1    Delta_AF7         312
2    Delta_AF8         312
3   Delta_TP10         312
4    Theta_TP9         312
5    Theta_AF7         312
6    Theta_AF8         312
7   Theta_TP10         312
8    Alpha_TP9         312
9    Alpha_AF7         312
10   Alpha_AF8         312
11  Alpha_TP10         312
12    Beta_TP9         312
13    Beta_AF7         312
14    Beta_AF8         312
15   Beta_TP10         312
16   Gamma_TP9         312
17   Gamma_AF7         312
18   Gamma_AF8         312
19  Gamma_TP10         312

23_EEG.csv -

   Column Name  Null Count
0    Delta_TP9        1161
1    Delta_AF7        1161
2    Delta_AF8        1161
3   Delta_TP10        1161
4    Theta_TP9        1161
5    Theta_AF7        1161
6    Theta_AF8        1161
7   Theta_TP10        1161
8    Alpha_TP9        1161
9    Alpha_AF7        1161
10   Alpha_AF8        1161
11  Alpha_TP10        1161
12    Beta_TP9        1161
13    Beta_AF7        1161
14    Beta_AF8        1161
15   Beta_TP10        1161
16   Gamma_TP9        1161
17   Gamma_AF7        1161
18   Gamma_AF8        1161
19  Gamma_TP10        1161

24_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         167
1    Delta_AF7         167
2    Delta_AF8         167
3   Delta_TP10         167
4    Theta_TP9         167
5    Theta_AF7         167
6    Theta_AF8         167
7   Theta_TP10         167
8    Alpha_TP9         167
9    Alpha_AF7         167
10   Alpha_AF8         167
11  Alpha_TP10         167
12    Beta_TP9         167
13    Beta_AF7         167
14    Beta_AF8         167
15   Beta_TP10         167
16   Gamma_TP9         167
17   Gamma_AF7         167
18   Gamma_AF8         167
19  Gamma_TP10         167

25_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         609
1    Delta_AF7         609
2    Delta_AF8         609
3   Delta_TP10         609
4    Theta_TP9         609
5    Theta_AF7         609
6    Theta_AF8         609
7   Theta_TP10         609
8    Alpha_TP9         609
9    Alpha_AF7         609
10   Alpha_AF8         609
11  Alpha_TP10         609
12    Beta_TP9         609
13    Beta_AF7         609
14    Beta_AF8         609
15   Beta_TP10         609
16   Gamma_TP9         609
17   Gamma_AF7         609
18   Gamma_AF8         609
19  Gamma_TP10         609

26_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         155
1    Delta_AF7         155
2    Delta_AF8         155
3   Delta_TP10         155
4    Theta_TP9         155
5    Theta_AF7         155
6    Theta_AF8         155
7   Theta_TP10         155
8    Alpha_TP9         155
9    Alpha_AF7         155
10   Alpha_AF8         155
11  Alpha_TP10         155
12    Beta_TP9         155
13    Beta_AF7         155
14    Beta_AF8         155
15   Beta_TP10         155
16   Gamma_TP9         155
17   Gamma_AF7         155
18   Gamma_AF8         155
19  Gamma_TP10         155

27_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         187
1    Delta_AF7         187
2    Delta_AF8         187
3   Delta_TP10         187
4    Theta_TP9         187
5    Theta_AF7         187
6    Theta_AF8         187
7   Theta_TP10         187
8    Alpha_TP9         187
9    Alpha_AF7         187
10   Alpha_AF8         187
11  Alpha_TP10         187
12    Beta_TP9         187
13    Beta_AF7         187
14    Beta_AF8         187
15   Beta_TP10         187
16   Gamma_TP9         187
17   Gamma_AF7         187
18   Gamma_AF8         187
19  Gamma_TP10         187

28_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         153
1    Delta_AF7         153
2    Delta_AF8         153
3   Delta_TP10         153
4    Theta_TP9         153
5    Theta_AF7         153
6    Theta_AF8         153
7   Theta_TP10         153
8    Alpha_TP9         153
9    Alpha_AF7         153
10   Alpha_AF8         153
11  Alpha_TP10         153
12    Beta_TP9         153
13    Beta_AF7         153
14    Beta_AF8         153
15   Beta_TP10         153
16   Gamma_TP9         153
17   Gamma_AF7         153
18   Gamma_AF8         153
19  Gamma_TP10         153

29_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         656
1    Delta_AF7         656
2    Delta_AF8         656
3   Delta_TP10         656
4    Theta_TP9         656
5    Theta_AF7         656
6    Theta_AF8         656
7   Theta_TP10         656
8    Alpha_TP9         656
9    Alpha_AF7         656
10   Alpha_AF8         656
11  Alpha_TP10         656
12    Beta_TP9         656
13    Beta_AF7         656
14    Beta_AF8         656
15   Beta_TP10         656
16   Gamma_TP9         656
17   Gamma_AF7         656
18   Gamma_AF8         656
19  Gamma_TP10         656

30_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         314
1    Delta_AF7         314
2    Delta_AF8         314
3   Delta_TP10         314
4    Theta_TP9         314
5    Theta_AF7         314
6    Theta_AF8         314
7   Theta_TP10         314
8    Alpha_TP9         314
9    Alpha_AF7         314
10   Alpha_AF8         314
11  Alpha_TP10         314
12    Beta_TP9         314
13    Beta_AF7         314
14    Beta_AF8         314
15   Beta_TP10         314
16   Gamma_TP9         314
17   Gamma_AF7         314
18   Gamma_AF8         314
19  Gamma_TP10         314

31_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         138
1    Delta_AF7         138
2    Delta_AF8         138
3   Delta_TP10         138
4    Theta_TP9         138
5    Theta_AF7         138
6    Theta_AF8         138
7   Theta_TP10         138
8    Alpha_TP9         138
9    Alpha_AF7         138
10   Alpha_AF8         138
11  Alpha_TP10         138
12    Beta_TP9         138
13    Beta_AF7         138
14    Beta_AF8         138
15   Beta_TP10         138
16   Gamma_TP9         138
17   Gamma_AF7         138
18   Gamma_AF8         138
19  Gamma_TP10         138

32_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         600
1    Delta_AF7         600
2    Delta_AF8         600
3   Delta_TP10         600
4    Theta_TP9         600
5    Theta_AF7         600
6    Theta_AF8         600
7   Theta_TP10         600
8    Alpha_TP9         600
9    Alpha_AF7         600
10   Alpha_AF8         600
11  Alpha_TP10         600
12    Beta_TP9         600
13    Beta_AF7         600
14    Beta_AF8         600
15   Beta_TP10         600
16   Gamma_TP9         600
17   Gamma_AF7         600
18   Gamma_AF8         600
19  Gamma_TP10         600

33_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         623
1    Delta_AF7         623
2    Delta_AF8         623
3   Delta_TP10         623
4    Theta_TP9         623
5    Theta_AF7         623
6    Theta_AF8         623
7   Theta_TP10         623
8    Alpha_TP9         623
9    Alpha_AF7         623
10   Alpha_AF8         623
11  Alpha_TP10         623
12    Beta_TP9         623
13    Beta_AF7         623
14    Beta_AF8         623
15   Beta_TP10         623
16   Gamma_TP9         623
17   Gamma_AF7         623
18   Gamma_AF8         623
19  Gamma_TP10         623

34_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         275
1    Delta_AF7         275
2    Delta_AF8         275
3   Delta_TP10         275
4    Theta_TP9         275
5    Theta_AF7         275
6    Theta_AF8         275
7   Theta_TP10         275
8    Alpha_TP9         275
9    Alpha_AF7         275
10   Alpha_AF8         275
11  Alpha_TP10         275
12    Beta_TP9         275
13    Beta_AF7         275
14    Beta_AF8         275
15   Beta_TP10         275
16   Gamma_TP9         275
17   Gamma_AF7         275
18   Gamma_AF8         275
19  Gamma_TP10         275

35_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         735
1    Delta_AF7         735
2    Delta_AF8         735
3   Delta_TP10         735
4    Theta_TP9         735
5    Theta_AF7         735
6    Theta_AF8         735
7   Theta_TP10         735
8    Alpha_TP9         735
9    Alpha_AF7         735
10   Alpha_AF8         735
11  Alpha_TP10         735
12    Beta_TP9         735
13    Beta_AF7         735
14    Beta_AF8         735
15   Beta_TP10         735
16   Gamma_TP9         735
17   Gamma_AF7         735
18   Gamma_AF8         735
19  Gamma_TP10         735

36_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         247
1    Delta_AF7         247
2    Delta_AF8         247
3   Delta_TP10         247
4    Theta_TP9         247
5    Theta_AF7         247
6    Theta_AF8         247
7   Theta_TP10         247
8    Alpha_TP9         247
9    Alpha_AF7         247
10   Alpha_AF8         247
11  Alpha_TP10         247
12    Beta_TP9         247
13    Beta_AF7         247
14    Beta_AF8         247
15   Beta_TP10         247
16   Gamma_TP9         247
17   Gamma_AF7         247
18   Gamma_AF8         247
19  Gamma_TP10         247

37_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         345
1    Delta_AF7         345
2    Delta_AF8         345
3   Delta_TP10         345
4    Theta_TP9         345
5    Theta_AF7         345
6    Theta_AF8         345
7   Theta_TP10         345
8    Alpha_TP9         345
9    Alpha_AF7         345
10   Alpha_AF8         345
11  Alpha_TP10         345
12    Beta_TP9         345
13    Beta_AF7         345
14    Beta_AF8         345
15   Beta_TP10         345
16   Gamma_TP9         345
17   Gamma_AF7         345
18   Gamma_AF8         345
19  Gamma_TP10         345

38_EEG.csv -

   Column Name  Null Count
0    Delta_TP9         280
1    Delta_AF7         280
2    Delta_AF8         280
3   Delta_TP10         280
4    Theta_TP9         280
5    Theta_AF7         280
6    Theta_AF8         280
7   Theta_TP10         280
8    Alpha_TP9         280
9    Alpha_AF7         280
10   Alpha_AF8         280
11  Alpha_TP10         280
12    Beta_TP9         280
13    Beta_AF7         280
14    Beta_AF8         280
15   Beta_TP10         280
16   Gamma_TP9         280
17   Gamma_AF7         280
18   Gamma_AF8         280
19  Gamma_TP10         280

=== Checking folder: GSR ===

1_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

2_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

3_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

4_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

5_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

6_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

7_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

8_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

9_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

10_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

11_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

12_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

13_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

14_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

15_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

16_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

17_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

18_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

19_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

20_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

21_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

22_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

23_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

24_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

25_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

26_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

27_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

28_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

29_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

30_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

31_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

32_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

33_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

34_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

35_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

36_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

37_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

38_GSR.csv -

           Column Name  Null Count
0   GSR Resistance CAL           4
1  GSR Conductance CAL           4

=== Checking folder: PSY ===

1_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

2_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

3_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

4_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

5_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           0

6_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           2

7_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

8_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

9_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

10_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

11_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           0

12_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           0

13_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           2

14_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

15_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

16_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           0

17_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

18_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           0

19_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           2

20_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

21_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

22_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

23_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

24_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

25_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

26_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

27_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

28_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

29_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

30_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

31_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

32_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

33_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           2

34_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           0

35_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

36_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           2

37_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           1

38_PSY.csv -

    Column Name  Null Count
0  routineStart           0
1    routineEnd           0
2    Difficulty           2

In [23]:
eeg_path = "../data/EEG"
gsr_path = "../data/GSR"
psy_path = "../data/PSY"
num_files = 38

folders = {
    "EEG": eeg_path,
    "GSR": gsr_path,
    "PSY": psy_path
}

for f_type, path in folders.items():
    print(f"\n=== {f_type} Data Types ===")
    for i in range(1, num_files + 1):
        file = os.path.join(path, f"{i}_{f_type}.csv")
        if not os.path.exists(file):
            print(f"[WARN] File not found: {file}")
            continue
        df = pd.read_csv(file)
        print(f"\nFile: {i}_{f_type}.csv")
        print(df.dtypes)

=== EEG Data Types ===

File: 1_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 2_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 3_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 4_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 5_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 6_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 7_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 8_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 9_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 10_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 11_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 12_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 13_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 14_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 15_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 16_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 17_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 18_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 19_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 20_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 21_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 22_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 23_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 24_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 25_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 26_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 27_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 28_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 29_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 30_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 31_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 32_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 33_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 34_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 35_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 36_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 37_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

File: 38_EEG.csv
Delta_TP9     float64
Delta_AF7     float64
Delta_AF8     float64
Delta_TP10    float64
Theta_TP9     float64
Theta_AF7     float64
Theta_AF8     float64
Theta_TP10    float64
Alpha_TP9     float64
Alpha_AF7     float64
Alpha_AF8     float64
Alpha_TP10    float64
Beta_TP9      float64
Beta_AF7      float64
Beta_AF8      float64
Beta_TP10     float64
Gamma_TP9     float64
Gamma_AF7     float64
Gamma_AF8     float64
Gamma_TP10    float64
Timestamp      object
dtype: object

=== GSR Data Types ===

File: 1_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 2_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 3_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 4_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 5_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 6_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 7_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 8_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 9_GSR.csv
GSR Resistance CAL     float64
GSR Conductance CAL    float64
Timestamp               object
dtype: object

File: 10_GSR.csv
GSR Resistance CAL     float64

In [30]:
eeg_folder = "../data/EEG"
gsr_folder = "../data/GSR"
output_folder = "../data/merged_data"
os.makedirs(output_folder, exist_ok=True)

num_students = 38

for i in range(1, num_students + 1):
    print(f"Merging EEG + GSR for student {i}...")

    eeg_file = os.path.join(eeg_folder, f"{i}_EEG.csv")
    gsr_file = os.path.join(gsr_folder, f"{i}_GSR.csv")
    
    if not (os.path.exists(eeg_file) and os.path.exists(gsr_file)):
        print(f"[WARN] Missing EEG or GSR file for student {i}, skipping.")
        continue
    
    # Load files
    eeg_df = pd.read_csv(eeg_file)
    gsr_df = pd.read_csv(gsr_file)
    
    # Merge based on UnixTime (nearest match)
    if "UnixTime" in eeg_df.columns and "UnixTime" in gsr_df.columns:
        merged_df = pd.merge_asof(
            eeg_df.sort_values("UnixTime"),
            gsr_df.sort_values("UnixTime"),
            on="UnixTime",
            direction="nearest"
        )
    else:
        merged_df = pd.concat([eeg_df, gsr_df], axis=1)
    
    # Save merged CSV
    output_file = os.path.join(output_folder, f"student_{i}.csv")
    merged_df.to_csv(output_file, index=False)

print("All students merged and saved in 'merged_data' folder.")

Merging EEG + GSR for student 1...
Merging EEG + GSR for student 2...
Merging EEG + GSR for student 3...
Merging EEG + GSR for student 4...
Merging EEG + GSR for student 5...
Merging EEG + GSR for student 6...
Merging EEG + GSR for student 7...
Merging EEG + GSR for student 8...
Merging EEG + GSR for student 9...
Merging EEG + GSR for student 10...
Merging EEG + GSR for student 11...
Merging EEG + GSR for student 12...
Merging EEG + GSR for student 13...
Merging EEG + GSR for student 14...
Merging EEG + GSR for student 15...
Merging EEG + GSR for student 16...
Merging EEG + GSR for student 17...
Merging EEG + GSR for student 18...
Merging EEG + GSR for student 19...
Merging EEG + GSR for student 20...
Merging EEG + GSR for student 21...
Merging EEG + GSR for student 22...
Merging EEG + GSR for student 23...
Merging EEG + GSR for student 24...
Merging EEG + GSR for student 25...
Merging EEG + GSR for student 26...
Merging EEG + GSR for student 27...
Merging EEG + GSR for student 28...
Merging EEG + GSR for student 29...
Merging EEG + GSR for student 30...
Merging EEG + GSR for student 31...
Merging EEG + GSR for student 32...
Merging EEG + GSR for student 33...
Merging EEG + GSR for student 34...
Merging EEG + GSR for student 35...
Merging EEG + GSR for student 36...
Merging EEG + GSR for student 37...
Merging EEG + GSR for student 38...
All students merged and saved in 'merged_data' folder.

In [ ]:
import pandas as pd
import numpy as np
import os
import logging

# Setup logging
logging.basicConfig(
    filename="per_trial_extraction.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

# Paths
merged_data_path = "merged_data"
psy_path = "PSY"
output_path = "data"
os.makedirs(output_path, exist_ok=True)

# Function to compute trial features
def compute_features(df, cols):
    stats = {}
    for col in cols:
        if col not in df.columns:
            logging.warning(f"Column {col} missing in trial slice.")
            continue
        stats[f"{col}_mean"] = df[col].mean()
        stats[f"{col}_std"] = df[col].std()
        stats[f"{col}_min"] = df[col].min()
        stats[f"{col}_max"] = df[col].max()
        stats[f"{col}_median"] = df[col].median()
    return stats

# Collect all trial-level data
all_trials = []

for pid in range(1, 39):  # 1 to 38 participants
    eeg_gsr_file = os.path.join(merged_data_path, f"student_{pid}.csv")
    psy_file = os.path.join(psy_path, f"{pid}_PSY.csv")

    if not os.path.exists(eeg_gsr_file):
        logging.error(f"Missing EEG+GSR file: {eeg_gsr_file}")
        continue
    if not os.path.exists(psy_file):
        logging.error(f"Missing PSY file: {psy_file}")
        continue

    # Load files
    try:
        eeg_gsr = pd.read_csv(eeg_gsr_file)
        psy = pd.read_csv(psy_file)
    except Exception as e:
        logging.error(f"Error reading files for participant {pid}: {e}")
        continue

    # Convert EEG+GSR timestamp to UNIX (if not already)
    try:
        eeg_gsr["UnixTime"] = pd.to_datetime(eeg_gsr["TimeStamp"], errors="coerce").astype("int64") // 10**9
    except Exception as e:
        logging.error(f"Error converting timestamps for participant {pid}: {e}")
        continue

    # Iterate over trials in PSY
    for _, trial in psy.iterrows():
        start, end = trial.get("routineStart"), trial.get("routineEnd")
        if pd.isna(start) or pd.isna(end):
            logging.warning(f"Missing start/end for trial in participant {pid}")
            continue

        trial_slice = eeg_gsr[(eeg_gsr["UnixTime"] >= start) & (eeg_gsr["UnixTime"] <= end)]
        if trial_slice.empty:
            logging.warning(f"No data found for participant {pid}, trial {trial.get('Key')}")
            continue

        # Select numeric EEG+GSR columns (exclude timestamp cols)
        numeric_cols = trial_slice.select_dtypes(include=[np.number]).columns.tolist()
        numeric_cols = [c for c in numeric_cols if c not in ["UnixTime"]]

        # Compute features
        trial_features = compute_features(trial_slice, numeric_cols)

        # Add identifiers + label
        trial_features.update({
            "Participant": pid,
            "TrialKey": trial.get("Key"),
            "Difficulty": trial.get("Difficulty", np.nan)
        })

        all_trials.append(trial_features)

# Save final per-trial dataset
final_df = pd.DataFrame(all_trials)
final_csv = os.path.join(output_path, "all_participants_features.csv")
final_df.to_csv(final_csv, index=False)

print(f"{final_csv}")

In [ ]:
# Load the CSV
file_path = '../data/all_partiipants_features.csv'
df = pd.read_csv(file_path)

# Fill numeric columns with mean
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

# Fill categorical/object columns with mode
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Overwrite the existing file
df.to_csv(file_path, index=False)

# Check if any nulls remain
print(df.isnull().sum())

EEG_Delta_TP9_mean                0
EEG_Delta_TP9_std                 0
EEG_Delta_TP9_min                 0
EEG_Delta_TP9_max                 0
EEG_Delta_TP9_median              0
                                 ..
GSR_GSR Conductance CAL_min       0
GSR_GSR Conductance CAL_max       0
GSR_GSR Conductance CAL_median    0
Participant                       0
Difficulty                        0
Length: 112, dtype: int64

In [9]:
import pandas as pd

# Load dataset
df = pd.read_csv('../data/all_participants_features.csv')

# Define custom mapping
difficulty_mapping = {
    'Difficult': 2,
    'Medium': 1,     
    'Easy': 0
}

# Apply mapping
df['difficulty_label'] = df['CognitiveLoad'].map(difficulty_mapping)

# Save back to CSV
df.to_csv('../data/all_participants_features.csv', index=False)